{
 "title": "Loki - Kong log",
 "tags": [ "legacy" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "[GET] access_log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/usr/local/kong/logs/access.log\"} |= `GET`"
    }
   ]
  },
  {
   "title": "[POST] access_log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/usr/local/kong/logs/access.log\"} |= `POST`"
    }
   ]
  },
  {
   "title": "[POST] admin_gui_access",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{filename=\"/usr/local/kong/logs/admin_gui_access.log\"} |= `POST`"
    }
   ]
  },
  {
   "title": "[GET] admin_gui_access_log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{filename=\"/usr/local/kong/logs/admin_gui_access.log\"} |= `GET`"
    }
   ]
  },
  {
   "title": "[POST] admin_access_log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{filename=\"/usr/local/kong/logs/admin_access.log\"} |= `POST`"
    }
   ]
  },
  {
   "title": "[POST] admin_access_log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{filename=\"/usr/local/kong/logs/admin_access.log\"} |= `POST`"
    }
   ]
  },
  {
   "title": "kong_error_log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{filename=\"/usr/local/kong/logs/error.log\"} |= ``"
    }
   ]
  },
  {
   "title": "bootstrap_log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/bootstrap.log\"} |= ``"
    }
   ]
  }
 ]
}