{
 "title": "Silicon RPC dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Silicon Batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "Silicon_Batch", "legendFormat": "Silicon Batch" },
    { "expr": "Silicon_Verified_Batch", "legendFormat": "Silicon Verified Batch" },
    { "expr": "Silicon_Virtual_Batch", "legendFormat": "Silicon Virtual Batch" }
   ]
  },
  {
   "title": "Increment batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "increase(Silicon_Batch[15m])", "legendFormat": "Silicon Batch" },
    {
     "expr": "increase(Silicon_Verified_Batch[1h])",
     "legendFormat": "Silicon Verified Batch"
    },
    {
     "expr": "increase(Silicon_Virtual_Batch[1h])",
     "legendFormat": "Silicon Virtual Batch"
    }
   ]
  },
  {
   "title": "Silicon_Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "Silicon_Block", "legendFormat": "Silicon_l2block" }
   ]
  },
  {
   "title": "increment block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "increase(Silicon_Block[2m])", "legendFormat": "__auto" }
   ]
  }
 ]
}