{
 "title": "[Tutorial] Prometheus Tutorial",
 "tags": [ "playground" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "##", "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 }, "options": { "content": "Just Basic Metric Query" } },
  {
   "title": "node_cpu_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    { "expr": "node_cpu_seconds_total" }
   ]
  },
  {
   "title": "##",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 10 },
   "options": {
    "content": "Basic Metric Query with Label Filtering"
   }
  },
  {
   "title": "node_cpu_seconds_total{chain=\"SUI\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{chain=\"SUI\"}"
    }
   ]
  },
  {
   "title": "node_cpu_seconds_total{chain=\"SUI\", servicetype=\"fullnode\"}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{chain=\"SUI\", servicetype=\"fullnode\"}"
    }
   ]
  },
  {
   "title": "##",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 29 },
   "options": {
    "content": "The per-second Average Rate of Increase of The Time Series in 1 minute."
   }
  },
  {
   "title": "rate(node_cpu_seconds_total{chain=\"SUI\", servicetype=\"fullnode\"}[1m])",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{chain=\"SUI\", servicetype=\"fullnode\"}[1m])"
    }
   ]
  },
  {
   "title": "##",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 39 },
   "options": {
    "content": "Sum of The per-second Average Rate of Increase of The Time Series in 1 minute."
   }
  },
  {
   "title": "sum (rate(node_cpu_seconds_total{chain=\"SUI\", servicetype=\"fullnode\"}[1m]))",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum (rate(node_cpu_seconds_total{chain=\"SUI\", servicetype=\"fullnode\"}[1m]))"
    }
   ]
  },
  {
   "title": "##",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 49 },
   "options": {
    "content": "Sum of The per-second Average Rate of Increase of The Time Series in 1 minute by network label."
   }
  },
  {
   "title": "sum by (network) (rate(node_cpu_seconds_total{chain=\"SUI\", servicetype=\"fullnode\"}[1m]))",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (network) (rate(node_cpu_seconds_total{chain=\"SUI\", servicetype=\"fullnode\"}[1m]))"
    }
   ]
  },
  {
   "title": "##",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 59 },
   "options": {
    "content": "Sum of The per-second Average Rate of Increase of The Time Series in 1 minute by network, instance label."
   }
  },
  {
   "title": "sum by (network, instance) (rate(node_cpu_seconds_total{chain=\"SUI\", servicetype=\"fullnode\"}[1m]))",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum by (network, instance) (rate(node_cpu_seconds_total{chain=\"SUI\", servicetype=\"fullnode\"}[1m]))"
    }
   ]
  }
 ]
}