{
 "title": "[Tutorial] Loki Tutorial",
 "tags": [ "playground" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "##", "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 }, "options": { "content": "Basic" } },
  { "title": "##", "type": "text", "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 }, "options": { "content": "Pipeline Filter Expression |= " } },
  {
   "title": "{chain=\"APT\"}",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "{chain=\"APT\"}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "{chain=\"APT\"} |= `\"request_uri\": \"/fullnode/v1/view\"`",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "{chain=\"APT\"} |= `\"request_uri\": \"/fullnode/v1/view\"`",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "##",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 10 },
   "options": {
    "content": "Pipeline Filter Expression with Json format"
   }
  },
  { "title": "##", "type": "text", "gridPos": { "h": 2, "w": 12, "x": 12, "y": 10 }, "options": { "content": "Pipeline Filter Expression != " } },
  {
   "title": "{chain=\"APT\"} | json | status=200",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{chain=\"APT\"} | json | status=200",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "{chain=\"APT\"} != `\"request_uri\": \"/fullnode/v1/view\"`",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{chain=\"APT\"} != `\"request_uri\": \"/fullnode/v1/view\"`",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "##",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 20 },
   "options": {
    "content": "Pipeline Filter Expression with Json Format and Comparison Operators"
   }
  },
  {
   "title": "##",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 20 },
   "options": {
    "content": "Pipeline Filter Expression with Json format"
   }
  },
  {
   "title": "{chain=\"APT\"} | json | status=200 | request_length > 300",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{chain=\"APT\"} | json | status=200 | request_length > 300 ",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "{chain=\"APT\"} != `\"request_uri\": \"/fullnode/v1/view\"` | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\"",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "{chain=\"APT\"} != `\"request_uri\": \"/fullnode/v1/view\"` | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\"",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "{chain=\"APT\"} | json | status=200 | request_length > 300 |= `\"request_uri\": \"/fullnode/v1/view\"`",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{chain=\"APT\"} | json | status=200 | request_length > 300 |= `\"request_uri\": \"/fullnode/v1/view\"`",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "{chain=\"APT\"} != `\"request_uri\": \"/fullnode/v1/view\"` | json | apikey!=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\"",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "{chain=\"APT\"} != `\"request_uri\": \"/fullnode/v1/view\"` | json | apikey!=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\"",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "##",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "Pipeline Filter Expression with Json Format and Comparison Operators and Logical Operators (maybe you can see No Data cuz it's not in time range you choose)"
   }
  },
  {
   "title": "{chain=\"APT\"} | json | status=200 | request_length > 300 |= `\"request_uri\": \"/fullnode/v1/view\"` |  msec > 1689284000 and  msec < 1689294000",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{chain=\"APT\"} | json | status=200 | request_length > 300 |= `\"request_uri\": \"/fullnode/v1/view\"` |  msec > 1689284000 and  msec < 1689294000",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "##",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "Pipeline Filter Expression with Json Format and Comparison and Logical Operators (maybe you can see No Data cuz it's not in time range you choose). You can change log format with line_format expression."
   }
  },
  {
   "title": "{chain=\"APT\"} | json | status=200 | request_length > 300 |= `\"request_uri\": \"/fullnode/v1/view\"` |  msec > 1689284000 and  msec < 1689294000 | line_format \"status {{.status}}, request body {{.request_body}}\"",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "{chain=\"APT\"} | json | status=200 | request_length > 300 |= `\"request_uri\": \"/fullnode/v1/view\"` |  msec > 1689284000 and  msec < 1689294000 | line_format \"status {{.status}}, request body {{.request_body}}\"",
     "maxLines": 100
    }
   ]
  }
 ]
}