{
 "title": "Usage Insights - 2 - Data sources",
 "description": "Dashboard surfacing details on datasource usage in Grafana Cloud. Uses provisioned Loki and Prometheus datasources.",
 "tags": [ "grafanacloud" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource_id", "label": "Data source ID", "query": "None" }
  ]
 },
 "panels": [
  {
   "title": "By query volume",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (datasourceId, datasourceName) (sum_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | datasourceName != \"-- Grafana --\" | datasourceName != \"-- Mixed --\" | unwrap totalQueries [$__range]))"
    }
   ]
  },
  {
   "title": "By error rate",
   "type": "table",
   "description": "Max error rate for the selected time period, may be different from the average error rate shown below.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (datasourceId, datasourceName) (count_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | datasourceName != \"-- Grafana --\" | datasourceName != \"-- Mixed --\" | error!=\"\" [$__range]))/sum by (datasourceId, datasourceName) (count_over_time({instance_type=\"grafana\"} | logfmt | datasourceName != \"-- Grafana --\" | datasourceName != \"-- Mixed --\" | eventName=\"data-request\" [$__range])) * 100"
    }
   ]
  },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (datasourceName) (count_over_time({instance_type=\"grafana\"} | logfmt | datasourceId=\"${datasource_id}\" [$__range]))"
    }
   ]
  },
  {
   "title": "ID",
   "type": "stat",
   "description": "This datasource ID is used in the underlying queries for this dashbaord. If you only have one stack, your datasource names will be unique. But, if you have more than one stack, you may have multiple datasources with the same name and must use this ID to query their metrics accurately.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (datasourceId) (count_over_time({instance_type=\"grafana\"} | logfmt | datasourceId=\"${datasource_id}\" [$__range]))"
    }
   ]
  },
  {
   "title": "Host Stack Name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id) (count_over_time({instance_type=\"grafana\"} | logfmt | datasourceId=\"${datasource_id}\" [$__range]))"
    },
    {
     "expr": "label_replace(sum(grafanacloud_grafana_instance_info{}) by (id, slug), \"instance_id\", \"$1\", \"id\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "stat",
   "description": "Dashboards and users querying this data source, total queries, cache rate, and error rate.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(sum by (dashboardId) (count_over_time({instance_type=\"grafana\"} | logfmt | datasourceId=\"${datasource_id}\" | eventName=\"data-request\" [$__range])))"
    },
    {
     "expr": "count(sum by (username) (count_over_time({instance_type=\"grafana\"} | logfmt | datasourceId=\"${datasource_id}\" | eventName=\"data-request\" [$__range])))"
    },
    {
     "expr": "sum(sum_over_time({instance_type=\"grafana\"} | logfmt | datasourceId=\"${datasource_id}\" | eventName=\"data-request\" | unwrap totalQueries [$__range]))"
    },
    {
     "expr": "100 * sum(sum_over_time({instance_type=\"grafana\"} | logfmt | datasourceId=\"${datasource_id}\" | eventName=\"data-request\" | unwrap cachedQueries [$__range])) / sum(sum_over_time({instance_type=\"grafana\"} | logfmt | datasourceId=\"${datasource_id}\" | eventName=\"data-request\" | unwrap totalQueries [$__range]))"
    },
    {
     "expr": "100 * sum(count_over_time({instance_type=\"grafana\"} | logfmt | datasourceId=\"${datasource_id}\" | eventName=\"data-request\" | error!=\"\" [$__range])) / sum(count_over_time({instance_type=\"grafana\"} | logfmt | datasourceId=\"${datasource_id}\" | eventName=\"data-request\" [$__range]))"
    }
   ]
  },
  {
   "title": "Data source requests over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(host) (sum_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | datasourceId=\"${datasource_id}\" | error = \"\" | unwrap totalQueries [$__interval]))",
     "legendFormat": "Data Requests"
    },
    {
     "expr": "sum by(host) (count_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | datasourceId=\"${datasource_id}\" | error != \"\" [$__interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "95th percentile of request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | error=\"\" | datasourceId=\"${datasource_id}\" | unwrap duration | __error__=\"\" [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max(max_over_time({instance_type=\"grafana\"} | logfmt | eventName=\"data-request\" | error=\"\" | datasourceId=\"${datasource_id}\" | unwrap duration | __error__=\"\" [$__interval])) by (host)",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "Top error types",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (error) (count_over_time({instance_type=\"grafana\"} | logfmt | error!=\"\" | datasourceId=\"${datasource_id}\" [$__range]))"
    }
   ]
  },
  {
   "title": "Users by queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (username) (sum_over_time({instance_type=\"grafana\"} | logfmt | datasourceId=\"${datasource_id}\" | eventName=\"data-request\" | datasourceName != \"-- Grafana --\" | datasourceName != \"-- Mixed --\" | unwrap totalQueries [$__range]))"
    }
   ]
  },
  {
   "title": "Dashboards by queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by (folderName, dashboardName,dashboardId) (sum_over_time({instance_type=\"grafana\"} | logfmt | datasourceId=\"${datasource_id}\" | eventName=\"data-request\" | dashboardName != \"\" | unwrap totalQueries [$__range]))"
    }
   ]
  },
  {
   "title": "Users with errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (username) (count_over_time({instance_type=\"grafana\"} | logfmt | datasourceId=\"${datasource_id}\" | eventName=\"data-request\" | error!=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Dashboards with errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by (folderName, dashboardName,dashboardId) (count_over_time({instance_type=\"grafana\"} | logfmt | datasourceId=\"${datasource_id}\" | eventName=\"data-request\" | dashboardName != \"\" | error != \"\" [$__range]))"
    }
   ]
  }
 ]
}