{
 "title": "Cosmos_Validator_Performance",
 "description": "A Grafana dashboard compatible with all the cosmos-sdk and tendermint based blockchains.",
 "tags": [
  "cosmos",
  "validator",
  "🚨 P1 ⚠️"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"BERA|DYDX|TIA|BALON\"},chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\"},network)"
    }
   },
   {
    "name": "servicetype",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\"},servicetype)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\"},job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\", servicetype=~\"$servicetype\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$chain overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "<img width=\"500\" src=\"https://raw.githubusercontent.com/Jaemin820/grafana-cosmos-dashboard/main/logo/$chain.jpg\" />"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "$chain Foundation $network $servicetype Block Height vs $chain $network $servicetype Block Height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "Chains_Foundation_Block_Height{chain=\"$chain\", network=\"$network\"}",
     "legendFormat": "Foundation Block Height - {{network}}"
    },
    {
     "expr": "cometbft_consensus_height{chain=\"$chain\", network=\"$network\", instance=\"$instance:26660\"}",
     "legendFormat": "Our Block Height - {{network}} - {{region}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{chain=\"$chain\", instance=\"$instance:26660\"}"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_block_interval_seconds_sum{chain=\"$chain\", instance=\"$instance:26660\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Bonded Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain=\"$chain\", instance=\"$instance:26660\"}"
    }
   ]
  },
  {
   "title": "Syncing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "cometbft_consensus_state_syncing{chain=\"$chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed Blocks Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_missed_blocks{chain=~\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Height Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_last_signed_height{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "cometbft_consensus_missing_validators_power{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "cometbft_consensus_byzantine_validators_power{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "cometbft_consensus_missing_validators{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "cometbft_consensus_byzantine_validators{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Online validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators-cometbft_consensus_missing_validators{chain='$chain', instance=\"$instance:26660\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Offline validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Total bonded tokens",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Missed Block",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_missed_blocks{job=~\"$job\",chain=~\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks / min",
   "type": "timeseries",
   "description": "Number of block produced last minute",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(cometbft_consensus_height{chain=\"$chain\", instance=\"$instance:26660\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nº validators",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "instance overview: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{chain=\"$chain\", instance=~\"$instance:26660\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{chain=\"$chain\", instance=~\"$instance:26660\"}"
    }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_failed_txs{chain=\"$chain\", instance=~\"$instance:26660\"}"
    }
   ]
  },
  {
   "title": "Recheck Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_recheck_times{chain=\"$chain\", instance=~\"$instance:26660\"}"
    }
   ]
  },
  {
   "title": "Total Network Input",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "rate(cometbft_p2p_peer_receive_bytes_total{chain=\"$chain\", instance=\"$instance:26660\"}[$__rate_interval])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "rate(cometbft_p2p_peer_send_bytes_total{chain=\"$chain\", instance=\"$instance:26660\"}[$__rate_interval])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}