{
 "title": "ICP_Nodes_Status",
 "tags": [ "🚨 P1 ⚠️" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "IC API Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ic_node_api_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ic_node_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node Provider ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ic_node_count", "legendFormat": "{{node_provider_id}}" }
   ]
  },
  {
   "title": "Node Status Overview",
   "type": "stat",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ic_node_status", "legendFormat": "{{node_id}}" }
   ]
  }
 ]
}