{
 "title": "Metapixel APTOS mempool",
 "tags": [
  "aptos-core",
  "legacy"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"APT\"}, chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\"}, network)"
    }
   },
   {
    "name": "servicetype",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\"}, servicetype)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(up{chain=~\"$chain\", network=~\"$network\",servicetype=~\"$servicetype\"}, region)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{chain=~\"$chain\", network=~\"$network\",servicetype=~\"$servicetype\", region=~\"$region\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "nodeID",
    "label": "nodeID",
    "query": {
     "query": "label_values(aptos_connections{direction=\"inbound\"},peer_id)"
    }
   },
   {
    "name": "chainAPI",
    "query": {
     "query": "CollectionLookup(mainnet,mainnet.aptoslabs.com,llt,testnet.aptoslabs.com,$chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mempool size",
   "type": "timeseries",
   "description": "total number of transactions in mempool",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by ( instance) (aptos_core_mempool_index_size{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", index=\"system_ttl\"})",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Mempool size (summary)",
   "type": "timeseries",
   "description": "total number of transactions in mempool",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(aptos_core_mempool_index_size{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", index=\"system_ttl\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "quantile(0.5, aptos_core_mempool_index_size{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", index=\"system_ttl\"})",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.9, aptos_core_mempool_index_size{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", index=\"system_ttl\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "quantile(0.99, aptos_core_mempool_index_size{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", index=\"system_ttl\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(0.1, aptos_core_mempool_index_size{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", index=\"system_ttl\"})",
     "legendFormat": "p10"
    }
   ]
  },
  {
   "title": "Active Upstream Peers",
   "type": "timeseries",
   "description": "number of live peers a node can broadcast to in each network",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, network) (aptos_mempool_active_upstream_peers_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"})",
     "legendFormat": "{{instance}}:{{role}}  ({{network}} network)"
    }
   ]
  },
  {
   "title": "Mempool size (bytes)",
   "type": "timeseries",
   "description": "total size in bytes of transactions in mempool",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by ( instance) (aptos_core_mempool_index_size{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", index=\"size_bytes\"})",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "(deprecated) Avg E2E Txn Commit Latency",
   "type": "timeseries",
   "description": "The time between Mempool receiving the transaction and time to be committed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval]) / rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "max(rate(aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval]) / rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval]))",
     "legendFormat": "max"
    },
    {
     "expr": "quantile(0.5, rate(aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval]) / rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval]))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.9, rate(aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval]) / rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval]))",
     "legendFormat": "p90"
    },
    {
     "expr": "quantile(0.1, rate(aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval]) / rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval]))",
     "legendFormat": "p10"
    }
   ]
  },
  {
   "title": "Per Bucket Avg E2E Txn Commit Latency",
   "type": "timeseries",
   "description": "The time between Mempool receiving the transaction and time to be committed.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval])) / sum by (bucket) (rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval]))",
     "legendFormat": "{{bucket}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Client-submitted E2E Txn latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\", submitted_by=\"client\"}[$interval])) / sum by (instance) (rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\", submitted_by=\"client\"}[$interval]))",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Validator E2E Txn Commit Latency",
   "type": "timeseries",
   "description": "Transactions that were submitted from downstream, and not from a peer validator",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance, submitted_by) (rate(aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", instance=~\"$instance\",  stage=\"commit_accepted\", submitted_by=\"downstream\"}[$interval])) / sum by (instance, submitted_by) (rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", instance=~\"$instance\",  stage=\"commit_accepted\", submitted_by=\"downstream\"}[$interval]))",
     "legendFormat": "{{instance}}:{{role}}:{{submitted_by}}"
    }
   ]
  },
  {
   "title": "Per Bucket E2E Txn Commit Latency",
   "type": "timeseries",
   "description": "The time between Mempool receiving the transaction and time to be committed.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by ( instance) (rate(aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval])) / sum by ( instance) (rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval]))",
     "legendFormat": "{{bucket}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Parking Lot Index",
   "type": "timeseries",
   "description": "number of transactions in parking lot index. These transactions are not ready for broadcast or consensus",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_core_mempool_index_size{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", index=\"parking_lot\"}",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Priority Index",
   "type": "timeseries",
   "description": "transactions ready for consensus",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by ( instance) (aptos_core_mempool_index_size{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\",index=\"priority\"})",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Timeline Index",
   "type": "timeseries",
   "description": "number of transactions ready for broadcast in core mempool ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_core_mempool_index_size{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", index=\"timeline\"}",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Timeline Index per Bucket",
   "type": "timeseries",
   "description": "Bucketed view of timeline index size",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_core_mempool_timeline_index_size{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}",
     "legendFormat": "{{instance}}:{{role}}:{{bucket}}"
    }
   ]
  },
  { "title": "Txn timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Avg Insertion-to-Consensus-Ready",
   "type": "timeseries",
   "description": "The time between the local Mempool receiving the transaction and time to be committed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) ((aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"consensus_ready\", scope=\"e2e\"}[$interval])) / sum by (instance) ((aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"consensus_ready\", scope=\"e2e\"}[$interval]))",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Avg Insertion-to-Consensus-Pulled",
   "type": "timeseries",
   "description": "The time between the local Mempool receiving the transaction and time to be committed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance, bucket) (rate(aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"consensus_pulled\"}[$interval])) / sum by (instance, bucket) (rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"consensus_pulled\"}[$interval]))",
     "legendFormat": "{{instance}}:{{role}}:{{bucket}}"
    }
   ]
  },
  {
   "title": "Avg Insertion-to-Block-Timestamp",
   "type": "timeseries",
   "description": "The time between the local Mempool receiving the transaction and time to be committed.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance, bucket) (rate(aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted_block\"}[$interval])) / sum by (instance, bucket) (rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted_block\"}[$interval]))",
     "legendFormat": "{{instance}}:{{role}}:{{bucket}}"
    }
   ]
  },
  {
   "title": "Avg Insertion-to-Commit",
   "type": "timeseries",
   "description": "The time between the local Mempool receiving the transaction and time to be committed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance, bucket) (rate(aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval])) / sum by (instance, bucket) (rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval]))",
     "legendFormat": "{{instance}}:{{role}}:{{bucket}}"
    }
   ]
  },
  {
   "title": "Avg Insertion-to-Broadcast-Ready",
   "type": "timeseries",
   "description": "The time between the local Mempool receiving the transaction and time to be committed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"broadcast_ready\"}[$interval])) / sum by (instance) (rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"broadcast_ready\"}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg Insertion-to-Broadcast-Batched",
   "type": "timeseries",
   "description": "The time between the local Mempool receiving the transaction and time to be committed.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(aptos_core_mempool_txn_commit_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"broadcast_batched\"}[$interval])) / sum by (instance) (rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"broadcast_batched\"}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transaction Insertion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Received",
   "type": "timeseries",
   "description": "rate of new transactions received from other peers or JSON-RPC",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, network, sender) (rate(aptos_shared_mempool_transactions_processed{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval]))",
     "legendFormat": "{{instance}}:{{role}} <- ({{network}} network, {{sender}})"
    }
   ]
  },
  {
   "title": "VM Validation Succeeded",
   "type": "timeseries",
   "description": "rate of transactions that were successfully validated before mempool insertion\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, network, sender) (rate(aptos_shared_mempool_transactions_processed{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", status!=\"vm_validation\"}[$interval]))",
     "legendFormat": "{{instance}}:{{role}} <- ({{network}} network:{{sender}})"
    }
   ]
  },
  {
   "title": "VM Validation Failed",
   "type": "timeseries",
   "description": "rate of submitted txns that failed to pass the VM validation",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, network, sender) (rate(aptos_shared_mempool_transactions_processed{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", status=\"vm_validation\"}[$interval]))",
     "legendFormat": "{{instance}}:{{role}} <- ({{network}} network:{{sender}})"
    }
   ]
  },
  {
   "title": "Insertion Succeeded",
   "type": "timeseries",
   "description": "rate of mempool insertion of txn",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, status) (rate(aptos_shared_mempool_transactions_processed{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", status=\"success\"}[$interval]))",
     "legendFormat": "{{instance}}:{{role}} - {{status}}"
    }
   ]
  },
  {
   "title": "Insertion Failed",
   "type": "timeseries",
   "description": "rate of transactions that passed VM validation but were rejected from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_transactions_processed{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", status!=\"success\", status!=\"vm_validation\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} <- ({{network}} network:{{sender}}) -  {{status}}"
    }
   ]
  },
  {
   "title": "Duplicate (Idempotent)",
   "type": "timeseries",
   "description": "Rate at which duplicate (idempotent) txns are received at mempool",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_idempotent_txns_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  { "title": "Transaction Removal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Removal Rate",
   "type": "timeseries",
   "description": "Rate at which txns are removed (via commit) from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_removed_txns_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Commit Accepted",
   "type": "timeseries",
   "description": "rate of accepted committed transactions (notified from consensus)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_txn_commit_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval])\n",
     "legendFormat": "{{instance}}:{{bucket}}"
    }
   ]
  },
  {
   "title": "Commit Rejected",
   "type": "timeseries",
   "description": "rate of rejected committed transactions (notified from consensus)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_transactions_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"commit_rejected\"}[$interval])\n",
     "legendFormat": "{{instance}}:{{bucket}}"
    }
   ]
  },
  {
   "title": "Client-expired",
   "type": "timeseries",
   "description": "rate of number of transactions that expired in mempool based on client-specified expiration time",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_gc_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"client_expiration\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} : {{status}}"
    }
   ]
  },
  {
   "title": "System-expired",
   "type": "timeseries",
   "description": "Rate of number of transactions that expired in mempool based on mempool-specified expiration time",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_gc_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"system_ttl\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} : {{status}}"
    }
   ]
  },
  {
   "title": "Eager expire on",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_gc_eager_expire_event_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} : {{status}}"
    }
   ]
  },
  {
   "title": "Eager expire on rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_gc_eager_expire_event_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval]) / rate(aptos_core_mempool_gc_eager_expire_non_parked_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} : {{status}}"
    }
   ]
  },
  {
   "title": "Transaction Broadcasts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Broadcast Rate",
   "type": "timeseries",
   "description": "rate of transactions broadcasted to other peers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_transaction_broadcast_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} -> ({{network}})"
    }
   ]
  },
  {
   "title": "Average Broadcast Size",
   "type": "timeseries",
   "description": "average number of transactions in a single broadcast",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_transaction_broadcast_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval]) / rate(aptos_shared_mempool_transaction_broadcast_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} -> ({{network}})"
    }
   ]
  },
  {
   "title": "Average Broadcast Roundtrip Time",
   "type": "timeseries",
   "description": "average time b/w broadcast sent and ACK coming back for it",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_broadcast_roundtrip_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval]) / rate(aptos_shared_mempool_broadcast_roundtrip_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} -> ({{network}})"
    }
   ]
  },
  {
   "title": "Average Broadcast Execution Latency",
   "type": "timeseries",
   "description": "avg time it takes to execute a broadcast",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_broadcast_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval]) / rate(aptos_mempool_broadcast_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} -> ({{network}})"
    }
   ]
  },
  {
   "title": "Retry Rebroadcast",
   "type": "timeseries",
   "description": "rate of broadcasts that are retrying past broadcasts that received a retry ACK",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_rebroadcast_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"retry\", instance=~\"$instance\", role=~\"role\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} -> ({{network}})"
    }
   ]
  },
  {
   "title": "Broadcast Rate (requests/s)",
   "type": "timeseries",
   "description": "avg number of broadcasts / sec",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_broadcast_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} -> ({{network}})"
    }
   ]
  },
  {
   "title": "Expired Rebroadcast Rate",
   "type": "timeseries",
   "description": "rate of broadcasts that are retrying expired braodcasts (that did not get back an ACK in window of time)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_rebroadcast_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"expired\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} -> {{network}}"
    }
   ]
  },
  {
   "title": "Pending Broadcasts",
   "type": "timeseries",
   "description": "number of sent broadcasts awaiting an ACK",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, network) (aptos_shared_mempool_pending_broadcasts_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"})",
     "legendFormat": "{{instance}}:{{role}} -> ({{network}})"
    }
   ]
  },
  {
   "title": "Backpressure Broadcast",
   "type": "timeseries",
   "description": "rate of broadcasts that were executed as a backpressure broadcast",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_rebroadcast_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"backpressure\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} -> {{network}}"
    }
   ]
  },
  { "title": "Gas Ranking Score", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Bucketed Ranking Score (Insert)",
   "type": "timeseries",
   "description": "Rate of inserted transactions per ranking score bucket",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, bucket) (rate(aptos_core_mempool_txn_ranking_bucket{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"insert\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucketed Ranking Score (Consensus Pulled)",
   "type": "timeseries",
   "description": "Rate of consensus pulled transactions per ranking score bucket",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, bucket) (rate(aptos_core_mempool_txn_ranking_bucket{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"consensus_pulled\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucketed Ranking Score (Remove)",
   "type": "timeseries",
   "description": "Rate of removed transactions per ranking score bucket",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, bucket) (rate(aptos_core_mempool_txn_ranking_bucket{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"remove\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucketed Ranking Score (Broadcast Ready)",
   "type": "timeseries",
   "description": "Rate of broadcast ready transactions per ranking score bucket",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, bucket) (rate(aptos_core_mempool_txn_ranking_bucket{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"broadcast_ready\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucketed Ranking Score (Broadcast Batched)",
   "type": "timeseries",
   "description": "Rate of broadcast batched transactions per ranking score bucket",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, bucket) (rate(aptos_core_mempool_txn_ranking_bucket{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"broadcast_batched\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucketed Ranking Score (Remove) - Sum",
   "type": "timeseries",
   "description": "Rate of removed transactions per ranking score bucket",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status, bucket) (rate(aptos_core_mempool_txn_ranking_bucket{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"remove\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "End-to-end Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 },
   "collapsed": true,
   "panels": [
    {
     "title": "p10",
     "type": "timeseries",
     "description": "The time between Mempool receiving the transaction and time to be committed.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.10, sum by (instance, le) (rate(aptos_core_mempool_txn_commit_latency_bucket{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval])))",
       "legendFormat": "{{instance}}:{{role}}"
      }
     ]
    },
    {
     "title": "p50",
     "type": "timeseries",
     "description": "The time between Mempool receiving the transaction and time to be committed.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (instance, le) (rate(aptos_core_mempool_txn_commit_latency_bucket{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval])))",
       "legendFormat": "{{instance}}:{{role}}"
      }
     ]
    },
    {
     "title": "p90",
     "type": "timeseries",
     "description": "The time between Mempool receiving the transaction and time to be committed.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum by (instance, le) (rate(aptos_core_mempool_txn_commit_latency_bucket{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"commit_accepted\"}[$interval])))",
       "legendFormat": "{{instance}}:{{role}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block size",
   "type": "timeseries",
   "description": "Average size of consensus blocks pulled from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_transactions_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"get_block\"}[$interval]) / rate(aptos_mempool_service_transactions_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"get_block\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Block size in bytes",
   "type": "timeseries",
   "description": "Average size in bytes of consensus blocks pulled from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_bytes_get_block_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval]) / rate(aptos_mempool_service_bytes_get_block_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Avg latency for get_block",
   "type": "timeseries",
   "description": "Avg time it takes for consensus to pull block from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_latency_ms_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"get_block\", instance=~\"$instance\"}[$interval]) / rate(aptos_mempool_service_latency_ms_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"get_block\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commit Succeeded",
   "type": "timeseries",
   "description": "Rate of accepted transactions committed per second (notified from state sync)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_transactions_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"commit_accepted\"}[$interval])\n",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Commit Rejected",
   "type": "timeseries",
   "description": "Rate of accepted transactions committed per second (notified from state sync)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_transactions_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"commit_rejected\"}[$interval])\n",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Event Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Incoming events rate",
   "type": "timeseries",
   "description": "rate of shared mempool events from peers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_events{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} - {{event}}"
    }
   ]
  },
  {
   "title": "Main loop latency",
   "type": "timeseries",
   "description": "Duration of each run of the event loop",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_main_loop_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval]) / rate(aptos_mempool_main_loop_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Shared Mempool Task Start Latency",
   "type": "timeseries",
   "description": "average time it takes for mempool to start an async task",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_bounded_executor_spawn_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"start\"}[$interval]) / rate(aptos_mempool_bounded_executor_spawn_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", stage=\"start\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} - {{task}}"
    }
   ]
  },
  {
   "title": "Average VM Validation Latency",
   "type": "timeseries",
   "description": "avg time it takes to VM-validate txns in a submission",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_process_txn_breakdown_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", portion=\"vm_validation\"}[$interval]) / rate(aptos_mempool_process_txn_breakdown_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", portion=\"vm_validation\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Average DB Read Latency",
   "type": "timeseries",
   "description": "latency of db read when validating transaction",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_process_txn_breakdown_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", portion=\"storage_fetch\"}[$interval]) / rate(aptos_mempool_process_txn_breakdown_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", portion=\"storage_fetch\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Average Txn Processing Latency",
   "type": "timeseries",
   "description": "avg time it takes to process incoming transactions, per incoming submission",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_request_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval]) / rate(aptos_shared_mempool_request_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} <- ({{network}} network:{{sender}})"
    }
   ]
  },
  {
   "title": "Avg latency handle commit (accepted)",
   "type": "timeseries",
   "description": "average time it takes for mempool to process a commit of accepted transactions (sent from state sync)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_latency_ms_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"commit_accepted\"}[$interval]) / rate(aptos_mempool_service_latency_ms_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"commit_accepted\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Avg latency handle commit (rejected)",
   "type": "timeseries",
   "description": "avg time it takes to process committed rejected txns",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_latency_ms_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"commit_rejected\"}[$interval])/rate(aptos_mempool_service_latency_ms_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"commit_rejected\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Core Mempool Invariant Violation",
   "type": "timeseries",
   "description": "number of times core mempool invariant was violated",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_core_mempool_invariant_violated_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", instance=\"$instance\", role=\"$role\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mempool Service Timeout",
   "type": "timeseries",
   "description": "number of timeouts on a mempool service request (from consensus/state sync)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_service_latency_ms_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", result=\"fail\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} - {{type}}"
    }
   ]
  },
  {
   "title": "DB error",
   "type": "timeseries",
   "description": "number of times a DB error occurred",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_db_error_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "JSON RPC Callback Timeout",
   "type": "timeseries",
   "description": "number of timeouts in callback to JSON RPC",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_json_rpc_callback_fail_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Network Send Fail",
   "type": "timeseries",
   "description": "number of times a aptos network send failed",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_network_send_fail_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "VM Reconfiguration Failure",
   "type": "timeseries",
   "description": "number of times reconfiguration of VM failed",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_vm_reconfig_update_fail_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "ACKs Received",
   "type": "timeseries",
   "description": "rate of retry/backpressure ACKs received",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_shared_mempool_ack_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", direction=\"received\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} <- {{network}} - {{type}}"
    }
   ]
  },
  {
   "title": "Unexpected Network Messages",
   "type": "timeseries",
   "description": "rate of unexpected network messages received",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_unexpected_network_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}} <- {{network}}:{{peer}}"
    }
   ]
  },
  {
   "title": "Sent ACKs (backoff/retry)",
   "type": "timeseries",
   "description": "rate of backoff/retry ACKs sent",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_shared_mempool_ack_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", direction=\"sent\"}",
     "legendFormat": "{{instance}}:{{role}} -> {{network}} - {{type}}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 210 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Garbage Collection Event Rate",
   "type": "timeseries",
   "description": "Number of times garbage-collection event occurred (regardless of how many txns were actually removed in the event)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_gc_event_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", type=\"system_ttl\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "GC Latency",
   "type": "timeseries",
   "description": "how long a transaction stayed in mempool before being garbage-collected",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_core_mempool_gc_latency_sum{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])/rate(aptos_core_mempool_gc_latency_count{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Network Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 219 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages Queued",
   "type": "timeseries",
   "description": "Messages currently queued to be sent out",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (aptos_mempool_pending_network_events{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", state=\"enqueued\"}) - sum by (instance)  (aptos_mempool_pending_network_events{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", state=\"dequeued\"})",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Messages Enqueued Rate",
   "type": "timeseries",
   "description": "rate of messages being enqueued to be sent out",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_pending_network_events{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", state=\"enqueued\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Messages Dequeued Rate",
   "type": "timeseries",
   "description": "Rate of messages dequeued from mempool network sender",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_mempool_pending_network_events{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", state=\"dequeued\"}[$interval])",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  },
  {
   "title": "Dropped Messages",
   "type": "timeseries",
   "description": "number of messages dropped from mempool channel sender",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_mempool_pending_network_events{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", region=~\"$region\", state=\"dropped\"}",
     "legendFormat": "{{instance}}:{{role}}"
    }
   ]
  }
 ]
}