{
 "title": "Aptos_EconiaIndexer_Caddy",
 "description": "Dashboard set for Caddy proxy",
 "tags": [
  "caddy",
  "🔘 P3 ➖"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "deployment", "query": { "query": "label_values(up{}, deployment)" } },
   {
    "name": "chain",
    "query": {
     "query": "label_values(up{chain=~\"APT\"}, chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(up{chain=~\"$chain\"}, network)"
    }
   },
   {
    "name": "servicetype",
    "query": {
     "query": "label_values(up{chain=~\"$chain\", network=~\"$network\"}, servicetype)"
    }
   },
   {
    "name": "cloud",
    "query": {
     "query": "label_values(up{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", instance=~\"$instance.*\"}, cloud)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\"}, instance)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(up{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", instance=~\"$instance.*\"}, region)"
    }
   },
   {
    "name": "node_name",
    "query": {
     "query": "label_values(up{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", instance=~\"$instance.*\"}, node_name)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "HTTP(S) requests total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(caddy_http_requests_total{instance=~\"$host\",handler=~\"$handler\"}[5m])*10) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP(S) errors total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(caddy_http_request_errors_total{instance=~\"$host\",handler=~\"$handler\"}[5m])*10) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Median response size in bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(caddy_http_response_size_bytes_bucket{instance=~\"$host\"}[5m])))"
    }
   ]
  },
  {
   "title": "Median response duration in seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(caddy_http_response_duration_seconds_bucket[5m])))"
    }
   ]
  },
  {
   "title": "Request/Response duration seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{instance=~\"$host\",handler=~\"$handler\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Econdia API Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "Aptos_Econia_API_Status", "legendFormat": "__auto" }
   ]
  }
 ]
}