{
 "title": "Aptos_EconiaIndexer_Status",
 "tags": [
  "Websocket",
  "🚨 P1 ⚠️"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "deployment", "query": { "query": "label_values(up{}, deployment)" } },
   {
    "name": "chain",
    "query": {
     "query": "label_values(up{chain=~\"APT\"}, chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(up{chain=~\"$chain\"}, network)"
    }
   },
   {
    "name": "servicetype",
    "query": {
     "query": "label_values(up{servicetype=~\"econia_indexer\"}, servicetype)"
    }
   },
   {
    "name": "cloud",
    "query": {
     "query": "label_values(up{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\"},cloud)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Econia Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Aptos Econia API Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Aptos_Econia_API_Status{chain=~\"$chain\", network=~\"$network\"}",
     "legendFormat": "{{chain}} {{network}} {{region}}"
    }
   ]
  },
  {
   "title": "Aptos Econia Websocket Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Aptos_Econia_Websocket_Status{chain=~\"$chain\", network=~\"$network\"}",
     "legendFormat": "{{chain}} {{network}} {{region}}"
    }
   ]
  },
  {
   "title": "Aptos Econia Indexer Processor Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "Aptos_Econia_Indexer_Processor_Status{chain=~\"$chain\", network=~\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aptos Econia Indexer aggregator user Processor Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "Aptos_Econia_Indexer_Aggregator_User_Processed_Status{chain=~\"$chain\", network=~\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}