{
 "title": "Aptos_Econia_Indexer_Caddy_Log",
 "tags": [
  "Aptos",
  "Econia",
  "Indexer",
  "Loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values({job=\"caddy_access_log\"}, job)"
   },
   {
    "name": "chain",
    "query": "label_values({job=~\"$job\", chain=\"APT\"}, chain)"
   },
   {
    "name": "network",
    "query": "label_values({job=~\"$job\", chain=~\"$chain\"},network)"
   },
   {
    "name": "region",
    "query": "label_values({job=~\"$job\", chain=~\"$chain\", network=~\"$network\"}, region)"
   },
   {
    "name": "node_name",
    "query": "label_values({job=~\"$job\", chain=~\"$chain\", network=~\"$network\", region=~\"$region\"}, node_name)"
   },
   {
    "name": "filename",
    "query": "label_values({job=~\"$job\", chain=~\"$chain\", network=~\"$network\", region=~\"$region\", node_name=~\"$node_name\"}, filename)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP status codes over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=~\"$job\", chain=~\"$chain\", network=~\"$network\", region=~\"$region\", node_name=~\"$node_name\"} |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{job=~\"$job\", chain=~\"$chain\", network=~\"$network\", region=~\"$region\", node_name=~\"$node_name\"} | json | unwrap duration |  __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by (host) (max_over_time({job=~\"$job\", chain=~\"$chain\", network=~\"$network\", region=~\"$region\", node_name=~\"$node_name\"} | json | unwrap duration |  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "{job=~\"$job\", chain=~\"$chain\", network=~\"$network\", region=~\"$region\", node_name=~\"$node_name\"} | json | line_format \"➡️ {{.ts}} \\n {{.status}} \\n {{.request_uri}}\"",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Request per Remote IP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (request_remote_ip) (count_over_time({job=~\"$job\", chain=~\"$chain\", network=~\"$network\", region=~\"$region\", node_name=~\"$node_name\"} | json |  __error__=\"\" [1m]))"
    }
   ]
  },
  {
   "title": "Request per Request URI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (request_uri) (count_over_time({job=~\"$job\", chain=~\"$chain\", network=~\"$network\", region=~\"$region\", node_name=~\"$node_name\"} | json |  __error__=\"\" [1m]))"
    }
   ]
  }
 ]
}