{
 "title": "Aptos_Fullnode_API",
 "tags": [
  "Aptos",
  "Fullnode"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"APT\"}, chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\"}, network)"
    }
   },
   {
    "name": "servicetype",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\", servicetype=~\"[a-z0-9_]*fullnode\"}, servicetype)"
    }
   },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\",network=~\"$network\",servicetype=~\"$servicetype\"},job)"
    }
   },
   {
    "name": "nodename",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$instance:9100\"}, nodename)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\",servicetype=~\"$servicetype\", purpose!~\"update_message\"}, instance)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\",servicetype=~\"$servicetype\", purpose!~\"update_message\"}, region)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "nodeID",
    "label": "nodeID",
    "query": {
     "query": "label_values(aptos_connections{direction=\"inbound\"},peer_id)"
    }
   },
   {
    "name": "chainAPI",
    "query": {
     "query": "CollectionLookup(mainnet,mainnet.aptoslabs.com,llt,testnet.aptoslabs.com,$chain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests By Response Status Code",
   "type": "timeseries",
   "description": "All requests processed per second, including bad requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (network, instance, status, region) (rate(aptos_api_response_status_count{job=~\"$job\"}[$interval]))",
     "legendFormat": "{{status}} {{network}} {{region}} {{instance}}"
    }
   ]
  },
  {
   "title": "Requests by Endpoint",
   "type": "timeseries",
   "description": "Request count by endpoint per $interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (job, instance, operation_id) (rate(aptos_api_requests_count{job=~\"$job\"}[$interval]))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "Latency grouped by method",
   "type": "timeseries",
   "description": "Aggregated endpoints latency per $interval, can be filtered by $endpoint",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "repeat": "Datasource",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (method, le) (rate(aptos_api_requests_bucket{method=\"GET\",job=\"$job\"}[$interval])))",
     "legendFormat": "{{method}}-p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (method, le) (rate(aptos_api_requests_bucket{method=\"GET\",job=\"$job\"}[$interval])))",
     "legendFormat": "{{method}}-p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (method, le) (rate(aptos_api_requests_bucket{method=\"GET\",job=\"$job\"}[$interval])))",
     "legendFormat": "{{method}}-p99"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (method, le) (rate(aptos_api_requests_bucket{method=\"POST\",job=\"$job\"}[$interval])))",
     "legendFormat": "{{method}}-p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (method, le) (rate(aptos_api_requests_bucket{method=\"POST\",job=\"$job\"}[$interval])))",
     "legendFormat": "{{method}}-p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (method, le) (rate(aptos_api_requests_bucket{method=\"POST\",job=\"$job\"}[$interval])))",
     "legendFormat": "{{method}}-p99"
    }
   ]
  },
  {
   "title": "Counts by method",
   "type": "timeseries",
   "description": "Aggregated endpoints latency per $interval, can be filtered by $endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{job=~\"$job\",method=\"GET\"}[$interval]))",
     "legendFormat": "{{method}}-Total"
    },
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{job=~\"$job\",method=\"POST\"}[$interval]))",
     "legendFormat": "{{method}}-Total"
    },
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{job=~\"$job\",method=\"GET\", status=~\"2.*\"}[$interval]))",
     "legendFormat": "{{method}}-200s"
    },
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{job=~\"$job\",method=\"POST\", status=~\"2.*\"}[$interval]))",
     "legendFormat": "{{method}}-200s"
    },
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{job=~\"$job\",method=\"GET\", status=~\"4.*\"}[$interval]))",
     "legendFormat": "{{method}}-400s"
    },
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{job=~\"$job\",method=\"POST\", status=~\"4.*\"}[$interval]))",
     "legendFormat": "{{method}}-400s"
    },
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{job=~\"$job\",method=\"GET\", status=~\"5.*\"}[$interval]))",
     "legendFormat": "{{method}}-500s"
    },
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{job=~\"$job\",method=\"POST\", status=~\"5.*\"}[$interval]))",
     "legendFormat": "{{method}}-500s"
    }
   ]
  },
  {
   "title": "Server Internal Errors [500]",
   "type": "timeseries",
   "description": "Server Internal Errors (response code 500) while processing requests, grouped by endpoints",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(aptos_api_requests_count{job=~\"$job\",status=\"500\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Error Rate [500]",
   "type": "timeseries",
   "description": "500s over number of requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(aptos_api_requests_count{job=~\"$job\",status=\"500\"}[$interval])) / sum by (operation_id) (rate(aptos_api_requests_count[$interval]))"
    }
   ]
  },
  { "title": "Per API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "$operation_id Latency",
   "type": "timeseries",
   "description": "Aggregated endpoints latency per $interval, can be filtered by $endpoint",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "repeat": "operation_id",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (operation_id, le) (rate(aptos_api_requests_bucket{job=~\"$job\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (operation_id, le) (rate(aptos_api_requests_bucket{operation_id=~\"$operation_id\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (operation_id, le) (rate(aptos_api_requests_bucket{operation_id=~\"$operation_id\"}[$interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "$operation_id Call Volume",
   "type": "timeseries",
   "description": "Aggregated endpoints call volume per $interval, can be filtered by $endpoint",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "repeat": "operation_id",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job, instance, operation_id, le) (rate(aptos_api_requests_count{job=~\"$job\"}[$interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by (operation_id, le) (rate(aptos_api_requests_count{operation_id=~\"$operation_id\", status=~\"2.*\"}[$interval]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum by (operation_id, le) (rate(aptos_api_requests_count{operation_id=~\"$operation_id\", status!~\"2.*\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  }
 ]
}