{
 "title": "Havah_Planet_Health_Reward",
 "tags": [
  "Havah",
  "Planet"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Planet Reward",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "HVH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Havah_Planet_Total_Reward{chain=\"HVH\", servicetype=\"planet\"}",
     "legendFormat": "planet id : {{planet_id}}   Total Reward"
    }
   ]
  },
  {
   "title": "Havah Reward by Planet Id",
   "type": "table",
   "gridPos": { "h": 21, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (current_term_sequence, planet_id) (Havah_Planet_Reward{chain=\"HVH\", servicetype=\"planet\"})",
     "legendFormat": "round : {{chain}} planet Id : {{planetId}} ]]]]]"
    }
   ]
  },
  {
   "title": "Total Reward by Planet Id",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "HVH" } },
   "targets": [
    {
     "expr": "Havah_Planet_Total_Reward{chain=\"HVH\", servicetype=\"planet\"}",
     "legendFormat": "planet id : {{planet_id}}"
    }
   ]
  },
  {
   "title": "Havah Healthcheck",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "Havah_Planet_Healthcheck{ chain=\"HVH\", servicetype=\"planet\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}