{
 "title": "Polygon_CDK_DB",
 "tags": [
  "Polygon",
  "CDK"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "State DB에 요청하는 초당  SQL Query 개수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({job=\"state-db\"} [1s])"
    }
   ]
  },
  {
   "title": "State DB 전체 logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"state-db\"}  | json | line_format \"\u001b[35m{{.timestamp}}\u001b[0m \u001b[32m{{.remote_host}}\u001b[0m\\n{{.message}}\\n{{.detail}}\""
    }
   ]
  },
  {
   "title": "Sequencer가 State DB에 요청하는 쿼리 로그 (INSERT, UPDATE 만)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"state-db\"}  | json | remote_host=~\".*sequencer.*\"  | message=~\".*UPDATE|INSERT.*\" | line_format \"\u001b[35m{{.timestamp}}\u001b[0m \u001b[32m{{.remote_host}}\u001b[0m\\n{{.message}}\\n{{.detail}}\""
    }
   ]
  },
  {
   "title": "Sequence Sender logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"sequence-sender\"} | json | line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "State DB - batch Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM state.batch\nORDER BY batch_num DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "State DB - sequences Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM state.sequences\nORDER BY from_batch_num DESC\nLIMIT 501"
    }
   ]
  },
  {
   "title": "Aggregator logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"aggregator\"} | json | line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "State DB - l2block Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT batch_num, block_num, block_hash, parent_hash, state_root, received_at, created_at\nFROM state.l2block\nORDER BY block_num DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Recent L2 Batch Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT batch_num\nFROM state.batch\nORDER BY batch_num DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Recent L2 Block Number",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT l2_block_num\nFROM state.transaction\nORDER BY  l2_block_num DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Ethereum Tx Manager logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "{job=\"eth-tx-manager\"} | json | line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "State DB - receipt",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT block_num, tx_hash, contract_address, effective_gas_price, status, cumulative_gas_used, gas_used\nFROM state.receipt\nORDER BY block_num DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Recent L1 Block synced by Synchronizer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT block_num, received_at\nFROM state.block\nORDER BY block_num DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "State DB - transaction Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM state.transaction\nORDER BY  l2_block_num DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "1분 동안 생성된 monitored_txs 개수",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('minute', generated_time) AS minute,\n  COUNT(*) AS row_count\nFROM\n  generate_series(\n    (SELECT MIN(created_at) FROM monitored_txs),\n    (SELECT MAX(created_at) FROM monitored_txs),\n    '1 minute'\n  )\n  AS generated_time\nLEFT JOIN\n  monitored_txs ON generated_time <= created_at AND created_at < generated_time + interval '1 minute'\nGROUP BY\n  1\nORDER BY\n  1 DESC;"
    }
   ]
  },
  {
   "title": "Recent L1 Block Which Has Monitored Tx ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT block_num\nFROM state.monitored_txs_history\nORDER BY nonce DESC , updated_at DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "State DB - monitored_txs_history table",
   "type": "table",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT updated_at, owner, id, status, history, block_num, from_addr, to_addr, created_at, valid_from, valid_to\nFROM state.monitored_txs_history\nORDER BY nonce DESC , updated_at DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "State DB - virtual_batch Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM state.virtual_batch\nORDER BY batch_num DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "State DB - verified_batch Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 55 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM state.verified_batch\nORDER BY batch_num DESC\nLIMIT 100"
    }
   ]
  }
 ]
}