{
 "title": "Sui_Validator_Best_Practice_SLA",
 "tags": [ "🔶 P2 ✴️" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\",network=~\"$network\",servicetype=~\"$servicetype\"},job)"
    }
   },
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"SUI\"}, chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(node_uname_info{servicetype=~\"$servicetype\"}, network)"
    }
   },
   {
    "name": "servicetype",
    "query": {
     "query": "label_values(node_uname_info{servicetype=~\"validator\"}, servicetype)"
    }
   },
   {
    "name": "nodename",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$instance:9100\"}, nodename)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\",servicetype=~\"$servicetype\", purpose!~\"update_message\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "nodeID",
    "label": "nodeID",
    "query": {
     "query": "label_values(aptos_connections{direction=\"inbound\"},peer_id)"
    }
   },
   {
    "name": "chainAPI",
    "query": {
     "query": "CollectionLookup(mainnet,mainnet.aptoslabs.com,llt,testnet.aptoslabs.com,$chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average time to generate consensus proposal latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(proposer_batch_latency_sum{chain=~\"$chain\",network=~\"$network\", servicetype=~\"$servicetype\"}[5m]) / sum by (chain, deployment, direction, instance, job, network, servicetype) (rate(proposer_batch_latency_count{chain=~\"$chain\",network=~\"$network\", servicetype=~\"$servicetype\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cert processing latency: p95 shared objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(validator_service_handle_certificate_consensus_latency{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", pct=\"95\"}[5m:1m]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 8 },
   "options": {
    "content": "# Consensus reliability SLA (SLO > 1.0 proposal/sec)\nat least one certified Narwhal proposal a second."
   }
  },
  {
   "title": "Consensus reliability",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance,chain,deployment,direction,job,network,servicetype) (rate(certificates_created{instance=~\"$instance:9184\", network=~\"$network\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus reliability - Consensus proposal rate",
   "type": "timeseries",
   "description": "certificates_createdcounterincrementseverytimeavalidatorcertifiesa Narwhal proposal. The steady rate of certified Narwhal proposals is crucial for the reliable system operation. In a healthy system the validators generate at least one certified Narwhal proposal a second.",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance,chain,deployment,direction,job,network,servicetype) (rate(certificates_created{instance=~\"$instance:9184\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus reliability",
   "type": "timeseries",
   "description": "certificates_createdcounterincrementseverytimeavalidatorcertifiesa Narwhal proposal. The steady rate of certified Narwhal proposals is crucial for the reliable system operation. In a healthy system the validators generate at least one certified Narwhal proposal a second.",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance,chain,deployment,direction,job,network,servicetype) (rate(certificates_created{instance=~\"$instance:9184\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance,chain,deployment,direction,job,network,servicetype) (rate(consensus_proposed_blocks{instance=~\"$instance:9184\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus reliability",
   "type": "timeseries",
   "description": "certificates_createdcounterincrementseverytimeavalidatorcertifiesa Narwhal proposal. The steady rate of certified Narwhal proposals is crucial for the reliable system operation. In a healthy system the validators generate at least one certified Narwhal proposal a second.",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance,chain,deployment,direction,job,network,servicetype) (rate(certificates_created{instance=~\"$instance:9184\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance,chain,deployment,direction,job,network,servicetype) (rate(consensus_proposed_blocks{instance=~\"$instance:9184\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus reliability SLO Ratio for 7days",
   "type": "timeseries",
   "description": "\nratio of generated Narwhal proposal for 7days\n7일동안 SUI validator 가 Narwhal proposal mempool에 1초에 1번 이상 generate한 횟수 비율",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "count_over_time( sum by (instance,chain,deployment,direction,job,network,servicetype) (rate(certificates_created{instance=~\"$instance:9184\"}[5m]) > 1.0)[7d:5m]) / (12*24*7)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus reliability",
   "type": "timeseries",
   "description": "certificates_createdcounterincrementseverytimeavalidatorcertifiesa Narwhal proposal. The steady rate of certified Narwhal proposals is crucial for the reliable system operation. In a healthy system the validators generate at least one certified Narwhal proposal a second.",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance,chain,deployment,direction,job,network,servicetype) (rate(certificates_created{instance=~\"$instance:9184\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance,chain,deployment,direction,job,network,servicetype) (rate(consensus_proposed_blocks{instance=~\"$instance:9184\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 30 },
   "options": {
    "content": "# Consensus latency SLA (SLO < 10.0 sec)\n SLO is to stay below 10 sec"
   }
  },
  {
   "title": "Consensus latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance,job,chain,network,deployment,direction,servicetype) (rate(sequencing_certificate_latency_sum{ position=\"0\", instance=~\"$instance:9184\", network=~\"$network\"}[5m]))\n/ sum by (instance,job,chain,network,deployment,direction,servicetype) (rate(sequencing_certificate_latency_count{ position=\"0\", instance=~\"$instance:9184\", network=~\"$network\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus latency",
   "type": "timeseries",
   "description": "sequencing_certificate_latencyhistogrammeasuressequencing latencies of the transactions that are proposed to consensus by the given alidator. ************************************The average latency in the steady state\nis typically below 3 sec, hence the SLO is to stay below 10 sec.",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (instance,job,chain,network,deployment,direction,servicetype) (rate(sequencing_certificate_latency_sum{ position=\"0\", instance=~\"$instance:9184\"}[5m]))\n/ sum by (instance,job,chain,network,deployment,direction,servicetype) (rate(sequencing_certificate_latency_count{ position=\"0\", instance=~\"$instance:9184\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus latency",
   "type": "timeseries",
   "description": "certificates_createdcounterincrementseverytimeavalidatorcertifiesa Narwhal proposal. The steady rate of certified Narwhal proposals is crucial for the reliable system operation. In a healthy system the validators generate at least one certified Narwhal proposal a second.",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (instance,job,chain,network,deployment,direction,servicetype) (rate(sequencing_certificate_latency_sum{ position=\"0\", instance=~\"$instance:9184\"}[5m]))\n/ sum by (instance,job,chain,network,deployment,direction,servicetype) (rate(sequencing_certificate_latency_count{ position=\"0\", instance=~\"$instance:9184\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus latency",
   "type": "timeseries",
   "description": "certificates_createdcounterincrementseverytimeavalidatorcertifiesa Narwhal proposal. The steady rate of certified Narwhal proposals is crucial for the reliable system operation. In a healthy system the validators generate at least one certified Narwhal proposal a second.",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (instance,job,chain,network,deployment,direction,servicetype) (rate(sequencing_certificate_latency_sum{ position=\"0\", instance=~\"$instance:9184\"}[5m]))\n/ sum by (instance,job,chain,network,deployment,direction,servicetype) (rate(sequencing_certificate_latency_count{ position=\"0\", instance=~\"$instance:9184\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Latency SLO Ratio for 7days",
   "type": "timeseries",
   "description": "ratio of average latency which is below 3 sec for 7days",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "count_over_time( (sum by (instance,job,chain,network,deployment,direction,servicetype) (rate(sequencing_certificate_latency_sum{ position=\"0\", instance=~\"$instance:9184\"}[5m]))\n/ sum by (instance,job,chain,network,deployment,direction,servicetype) (rate(sequencing_certificate_latency_count{ position=\"0\", instance=~\"$instance:9184\"}[5m])) < 10.0)[7d:5m]) / (12*24*7)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus latency",
   "type": "timeseries",
   "description": "certificates_createdcounterincrementseverytimeavalidatorcertifiesa Narwhal proposal. The steady rate of certified Narwhal proposals is crucial for the reliable system operation. In a healthy system the validators generate at least one certified Narwhal proposal a second.",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (instance,job,chain,network,deployment,direction,servicetype) (rate(sequencing_certificate_latency_sum{ position=\"0\", instance=~\"$instance:9184\"}[5m]))\n/ sum by (instance,job,chain,network,deployment,direction,servicetype) (rate(sequencing_certificate_latency_count{ position=\"0\", instance=~\"$instance:9184\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 54 },
   "options": {
    "content": "# Execution latency SLA (SLO < 3.0 sec)\n SLO is to stay below 3 sec"
   }
  },
  {
   "title": "Execution latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance,deployment,direction,job,chain,network,servicetype) (rate (validator_service_handle_certificate_non_consensus_latency_sum{instance=~\"$instance:9184\", network=~\"$network\"}[5m]))/ sum by (instance,deployment,direction,job,chain,network,servicetype) (rate(validator_service_handle_certificate_non_consensus_latency_count{instance=~\"$instance:9184\", network=~\"$network\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution latency",
   "type": "timeseries",
   "description": "validator_service_handle_certificate_non_consensus_latency histogram measures the execution latency of the owned object certificates (the ones that do not rely on consensus on the critical path). The average latency in the state state is typically 500ms, hence the SLO is to stay below 3 sec",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (instance,deployment,direction,job,chain,network,servicetype) (rate (validator_service_handle_certificate_non_consensus_latency_sum{instance=~\"$instance:9184\"}[5m]))/ sum by (instance,deployment,direction,job,chain,network,servicetype) (rate(validator_service_handle_certificate_non_consensus_latency_count{instance=~\"$instance:9184\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution latency",
   "type": "timeseries",
   "description": "certificates_createdcounterincrementseverytimeavalidatorcertifiesa Narwhal proposal. The steady rate of certified Narwhal proposals is crucial for the reliable system operation. In a healthy system the validators generate at least one certified Narwhal proposal a second.",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (instance,deployment,direction,job,chain,network,servicetype) (rate (validator_service_handle_certificate_non_consensus_latency_sum{instance=~\"$instance:9184\"}[5m]))/ sum by (instance,deployment,direction,job,chain,network,servicetype) (rate(validator_service_handle_certificate_non_consensus_latency_count{instance=~\"$instance:9184\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution latency",
   "type": "timeseries",
   "description": "certificates_createdcounterincrementseverytimeavalidatorcertifiesa Narwhal proposal. The steady rate of certified Narwhal proposals is crucial for the reliable system operation. In a healthy system the validators generate at least one certified Narwhal proposal a second.",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (instance,deployment,direction,job,chain,network,servicetype) (rate (validator_service_handle_certificate_non_consensus_latency_sum{instance=~\"$instance:9184\"}[5m]))/ sum by (instance,deployment,direction,job,chain,network,servicetype) (rate(validator_service_handle_certificate_non_consensus_latency_count{instance=~\"$instance:9184\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Latency SLO for 7days",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "count_over_time((sum by (instance,deployment,direction,job,chain,network,servicetype) (rate (validator_service_handle_certificate_non_consensus_latency_sum{instance=~\"$instance:9184\"}[5m]))/ sum by (instance,deployment,direction,job,chain,network,servicetype) (rate(validator_service_handle_certificate_non_consensus_latency_count{instance=~\"$instance:9184\"}[5m])) < 3.0)[7d:5m]) / (12*24*7)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution latency",
   "type": "timeseries",
   "description": "certificates_createdcounterincrementseverytimeavalidatorcertifiesa Narwhal proposal. The steady rate of certified Narwhal proposals is crucial for the reliable system operation. In a healthy system the validators generate at least one certified Narwhal proposal a second.",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (instance,deployment,direction,job,chain,network,servicetype) (rate (validator_service_handle_certificate_non_consensus_latency_sum{instance=~\"$instance:9184\"}[5m]))/ sum by (instance,deployment,direction,job,chain,network,servicetype) (rate(validator_service_handle_certificate_non_consensus_latency_count{instance=~\"$instance:9184\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}