{
 "title": "Sui_Fullnode_Health",
 "tags": [ "🚨 P1 ⚠️" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"SUI\"}, chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\"}, network)"
    }
   },
   {
    "name": "servicetype",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\"}, servicetype)"
    }
   },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\",network=~\"$network\",servicetype=~\"$servicetype\"},job)"
    }
   },
   {
    "name": "nodename",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$instance:9100\"}, nodename)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\",network=~\"$network\",servicetype=~\"$servicetype\", job=~\"$job\",servicetype=~\"$servicetype\", purpose!~\"update_message\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "nodeID",
    "label": "nodeID",
    "query": {
     "query": "label_values(aptos_connections{direction=\"inbound\"},peer_id)"
    }
   },
   {
    "name": "chainAPI",
    "query": {
     "query": "CollectionLookup(mainnet,mainnet.aptoslabs.com,llt,testnet.aptoslabs.com,$chain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Fullnode Healthcheck Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aptos Fullnode Health Check [old version]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Sui_Fullnode_Healthcheck{chain=\"$chain\",network=\"mainnet\", purpose=\"custom_metric\", servicetype=\"fullnode\"} or Sui_Fullnode_Healthcheck{chain=\"$chain\",network=\"testnet\", purpose=\"custom_metric\", servicetype=\"fullnode\"}",
     "legendFormat": "{{ip}} {{exported_network}} {{region}}"
    }
   ]
  },
  {
   "title": "SUI Blockheight Overview by Domain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Sui Mainnet Fullnode Block Height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "Sui_Fullnode_Block_Height{chain=~\"$chain\", network=\"mainnet\", servicetype=\"fullnode\"}",
     "legendFormat": "{{servicetype}} [{{url}}]"
    }
   ]
  },
  {
   "title": "Sui Testnet Fullnode Block Height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "Sui_Fullnode_Block_Height{chain=~\"$chain\", network=\"testnet\", servicetype=\"fullnode\"}",
     "legendFormat": "{{service_type}} [{{url}}]"
    }
   ]
  },
  {
   "title": "Sui Mainnet Fullnode Block Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Sui_Fullnode_Block_Height{chain=~\"$chain\", network=\"mainnet\", servicetype=\"fullnode\", url=~\"https://.*mainnet.*\"}",
     "legendFormat": "{{servicetype}} [{{url}}]"
    }
   ]
  },
  {
   "title": "Sui Testnet Fullnode Block Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Sui_Fullnode_Block_Height{chain=~\"$chain\", network=\"testnet\", servicetype=\"fullnode\", url=~\"https://.*testnet.*\"}",
     "legendFormat": "{{servicetype}} [{{url}}]"
    }
   ]
  },
  { "title": "Overview [$network]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "network" },
  {
   "title": "Hardware Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_uname_info{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\" ,job=~\"$job\"} - 0"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\",job=~\"$job\"}) by (instance)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "node_memory_MemTotal_bytes{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", job=~\"$job\"} - 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", job=~\"$job\"}) by (instance) /8",
     "legendFormat": "Cores"
    },
    {
     "expr": "node_load5{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", job=~\"$job\"}",
     "legendFormat": "5m load"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", job=~\"$job\",mode=\"idle\"}[$__interval])) by (instance)) * 100",
     "legendFormat": "CPU used%"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", job=~\"$job\"} / (node_memory_MemTotal_bytes{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", job=~\"$job\"}))) * 100",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", job=~\"$job\"}[$__interval])) by (instance)",
     "legendFormat": "Disk read%"
    },
    {
     "expr": "100 - (sum(node_filesystem_avail_bytes{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", job=~\"$job\",mountpoint=~\"/\",fstype=~\"ext.?|xfs\"}/node_filesystem_size_bytes{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", job=~\"$job\",mountpoint=~\"/\",fstype=~\"ext.?|xfs\"}) by (instance)) * 100",
     "legendFormat": "/ used%"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", job=~\"$job\"}[$__interval])) by (instance)",
     "legendFormat": "Disk write%"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", job=~\"$job\"}[$__interval])*8) by (instance)",
     "legendFormat": "Download"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\", job=~\"$job\"}[$__interval])*8) by (instance)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "last executed checkpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "last_executed_checkpoint{chain=~\"$chain\", network=~\"$network\"}",
     "legendFormat": "{{servicetype}} [{{region}}] ({{instance}})"
    }
   ]
  },
  {
   "title": "last executed checkpoint",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 40 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_executed_checkpoint{chain=~\"$chain\", network=~\"$network\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{servicetype}} [{{region}}] ({{instance}})"
    }
   ]
  },
  {
   "title": "highest known checkpoint",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 40 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "highest_known_checkpoint{chain=~\"$chain\", network=~\"$network\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{servicetype}} [{{region}}] ({{instance}})"
    }
   ]
  },
  {
   "title": "highest synced checkpoint",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 40 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "highest_synced_checkpoint{chain=~\"$chain\", network=~\"$network\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{servicetype}} [{{region}}] ({{instance}})"
    }
   ]
  },
  {
   "title": "Indexer Fullnode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true
  }
 ]
}