{
 "title": "Sui Fullnode Hardware",
 "tags": [ "🔶 P2 ✴️" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"SUI\"}, chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\"}, network)"
    }
   },
   {
    "name": "servicetype",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\", servicetype=~\"[a-z_]*fullnode\"}, servicetype)"
    }
   },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\",network=~\"$network\",servicetype=~\"$servicetype\"},job)"
    }
   },
   {
    "name": "nodename",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$instance:9100\"}, nodename)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\"}, region)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\",servicetype=~\"$servicetype\",region=~\"$region\", purpose!~\"update_message\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "nodeID",
    "label": "nodeID",
    "query": {
     "query": "label_values(aptos_connections{direction=\"inbound\"},peer_id)"
    }
   },
   {
    "name": "chainAPI",
    "query": {
     "query": "CollectionLookup(mainnet,mainnet.aptoslabs.com,llt,testnet.aptoslabs.com,$chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Information for $hostname ($instance) - based on instance selection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 }, "options": { "content": "# ${hostname} (${instance})" } },
  {
   "title": "Server Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\",chain=~\"$chain\"} - 0"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\",chain=~\"$chain\"}) by (instance)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\",chain=~\"$chain\"} - 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\",chain=~\"$chain\"}) by (instance) /8",
     "legendFormat": "Cores"
    },
    {
     "expr": "node_load5{job=~\"$job\",chain=~\"$chain\"}",
     "legendFormat": "5m load"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",chain=~\"$chain\",mode=\"idle\"}[$__interval])) by (instance)) * 100",
     "legendFormat": "CPU used%"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\",chain=~\"$chain\"} / (node_memory_MemTotal_bytes{job=~\"$job\",chain=~\"$chain\"}))) * 100",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=~\"$job\",chain=~\"$chain\"}[$__interval])) by (instance)",
     "legendFormat": "Disk read%"
    },
    {
     "expr": "100 - (sum(node_filesystem_avail_bytes{job=~\"$job\",chain=~\"$chain\",mountpoint=~\"/\",fstype=~\"ext.?|xfs\"}/node_filesystem_size_bytes{job=~\"$job\",chain=~\"$chain\",mountpoint=~\"/\",fstype=~\"ext.?|xfs\"}) by (instance)) * 100",
     "legendFormat": "/ used%"
    },
    {
     "expr": "100 - (sum(node_filesystem_avail_bytes{job=~\"$job\",chain=~\"$chain\",mountpoint=~\"/home\",fstype=~\"ext.?|xfs\"}/node_filesystem_size_bytes{job=~\"$job\",chain=~\"$chain\",mountpoint=~\"/home\",fstype=~\"ext.?|xfs\"}) by (instance)) * 100",
     "legendFormat": "/home used%"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"$job\",chain=~\"$chain\"}[$__interval])) by (instance)",
     "legendFormat": "Disk write%"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=~\"$job\",chain=~\"$chain\"}[$__interval])*8) by (instance)",
     "legendFormat": "Download"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=~\"$job\",chain=~\"$chain\"}[$__interval])*8) by (instance)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$instance:.*\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance:.*\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$instance:.*\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$instance:.*\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=~\"$instance:.*\",job=\"$job\"}) / count(count(node_cpu_seconds_total{instance=~\"$instance:.*\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$instance:.*\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$instance:.*\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=~\"$instance:.*\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$instance:.*\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$instance:.*\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance:.*\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$instance:.*\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Extradisk FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance:.*\",job=\"$job\",mountpoint=\"/extradisk\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$instance:.*\",job=\"$job\",mountpoint=\"/extradisk\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$instance:.*\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:.*\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance:.*\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance:.*\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "HomeFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance:.*\",job=\"$job\",mountpoint=\"/home\",fstype!=\"rootfs\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$instance:.*\",job=\"$job\"} - node_boot_time_seconds{instance=~\"$instance:.*\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\"nice|steal\",instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"} - node_memory_MemFree_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"} - (node_memory_Cached_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"} + node_memory_Buffers_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"} + node_memory_Buffers_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance:.*\",chain=~\"$chain\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$instance:.*\",chain=~\"$chain\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$instance:.*\",chain=~\"$chain\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Disk R/W (kb/sec by device)",
   "type": "timeseries",
   "description": "The number of kibibytes read and written to the device  per second",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device!~\"md.*\",chain=~\"$chain\",instance=~\"$instance:.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} Read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device!~\"md.*\",chain=~\"$chain\",instance=~\"$instance:.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} Write"
    }
   ]
  },
  {
   "title": "Disk R/W (Requests/sec by device)",
   "type": "timeseries",
   "description": "The number of kibibytes read and written to the device  per second",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device!~\"md.*\",chain=~\"$chain\",instance=~\"$instance:.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} Read"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{device!~\"md.*\",chain=~\"$chain\",instance=~\"$instance:.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} Write"
    }
   ]
  },
  {
   "title": "Disk CPU Utilization (%)",
   "type": "timeseries",
   "description": "The percent of CPU time during which I/O requests were issued to the device",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$instance:.*\",chain=~\"$chain\",device!~\"md.*\"}[$__rate_interval])",
     "legendFormat": "{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Disk Latencies",
   "type": "timeseries",
   "description": "Time spent on each read/write operation (ignores individual \"md\" devices)",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$instance:.*\",chain=~\"$chain\",device!~\"md.*\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{instance=~\"$instance:.*\",chain=~\"$chain\",device!~\"md.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} Read Latency"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$instance:.*\",chain=~\"$chain\",device!~\"md.*\"}[$__rate_interval]) / rate(node_disk_writes_completed_total{instance=~\"$instance:.*\",chain=~\"$chain\",device!~\"md.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} Write Latency"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$instance:.*\",chain=~\"$chain\",device!~\"md.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} IO Time"
    },
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=~\"$instance:.*\",chain=~\"$chain\",device!~\"md.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} IO Weighted"
    }
   ]
  },
  {
   "title": "Disk Space (%)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~\"$instance:.*\",chain=~\"$chain\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Hardware Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"${job}\",chain=\"${chain}\",instance=~\"$instance:.*\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{job=\"${job}\",chain=\"${chain}\",instance=~\"$instance:.*\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "Systemd Service Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 38 },
   "targets": [
    {
     "expr": "node_systemd_units{job=\"${job}\",chain=\"${chain}\",instance=~\"$instance:.*\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance:.*\",chain=~\"$chain\"}[$__rate_interval])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance:.*\",chain=~\"$chain\"}[$__rate_interval])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Data Last Day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$instance:.*\",chain=~\"$chain\"}[24h]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$instance:.*\",chain=~\"$chain\"}[24h]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Open  File Descriptor (left) / Context switches (right)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$instance:.*\",chain=~\"$chain\"}",
     "legendFormat": "used filefd"
    },
    {
     "expr": "rate(node_context_switches_total{instance=~\"$instance:.*\",chain=~\"$chain\"}[$__rate_interval])",
     "legendFormat": "switches"
    }
   ]
  },
  {
   "title": "Data Last Week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$instance:.*\"}[7d]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$instance:.*\"}[7d]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Data Last Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$instance:.*\"}[31d]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$instance:.*\"}[31d]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}