{
 "title": "Sui_Validator_Status",
 "description": "Sui Validator Node dashboard. Uses Grafana agent with node exporter plugin/integration enabled. ",
 "tags": [
  "sui",
  "fullnode",
  "🚨 P1 ⚠️"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{chain=\"SUI\"}, chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\"}, network)"
    }
   },
   {
    "name": "servicetype",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\"}, servicetype)"
    }
   },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\", servicetype=~\"$servicetype\"}, job)"
    }
   },
   {
    "name": "nodename",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", region=~\"$region\"}, nodename)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, region)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", region=~\"$region\"}, instance)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 }, "options": { "content": "## Sui Metrics Dashboard" } },
  {
   "title": "Sui Client Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance, version) (uptime)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sui Node Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$instance:9100\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$instance:9100\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$instance:9100\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$instance:9100\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$instance:9100\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$instance:9100\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance:9100\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"$instance:9100\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance:9100\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance:9100\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$instance:9100\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$instance:9100\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$instance:9100\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$instance:9100\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance:9100\",job=\"$job\"} - node_boot_time_seconds{instance=\"$instance:9100\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance:9100\",job=\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$instance:9100\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance:9100\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$instance:9100\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance:9100\",job=\"$job\"}"
    }
   ]
  },
  { "title": "Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Input Objects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "num_input_objects_count{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Txns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_transaction_certificates{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Speed TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(total_transaction_certificates{job=~\"$job\", instance=~\"$instance:9184\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txns Effects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_transaction_effects{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest Checkpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "highest_known_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync'd Checkpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "highest_synced_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Epoch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_epoch{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Until Next epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(19000 - last_executed_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"} % 19000) / rate(last_executed_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoch Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "epoch_total_duration{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Validator Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_executed_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "Last Executed Checkpoint"
    },
    {
     "expr": "highest_synced_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "Highest Synced Checkpoint"
    },
    {
     "expr": "highest_verified_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "Highest Verified Checkpoint"
    },
    {
     "expr": "last_certified_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "Last Certified Checkpoint"
    },
    {
     "expr": "highest_known_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "Highest Known Checkpoint"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_round{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "Current Round"
    },
    {
     "expr": "highest_processed_round{source=\"own\", job=~\"$job\"}",
     "legendFormat": "Highest Processed Round"
    },
    {
     "expr": "transactions_included_in_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "Txns in Checkpoint"
    },
    {
     "expr": "total_transaction_orders{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "Total Txns Orders"
    },
    {
     "expr": "total_handle_certificate_attempts{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "Total Handle Certificate Attempts"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "primary_network_peers", "legendFormat": "Primary Network Peers" },
    {
     "expr": "worker_network_peers{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "Worker Network Peers"
    },
    {
     "expr": "sui_network_peers{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "Sui Network Peers"
    },
    {
     "expr": "skipped_consensus_txns{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "Skipped Consensus Txns"
    },
    {
     "expr": "total_signature_errors{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "Total Signature Errors"
    }
   ]
  },
  { "title": "Checkpointing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "highest_known_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "highest_verified_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "last_executed_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Highest Synced Checkpoint ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "highest_synced_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Checkpoint Execution Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "(last_executed_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"} - highest_known_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"})",
     "legendFormat": "checkpoint execution backlog"
    }
   ]
  },
  {
   "title": "Checkpoint Synchronization Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "(highest_synced_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}- highest_known_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"})",
     "legendFormat": "checkpoint execution backlog"
    }
   ]
  },
  {
   "title": "Last Executed Checkpoint (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "(rate(last_executed_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}[2m]))",
     "legendFormat": "checkpoint execution backlog"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Certificates Created (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "(rate(certificates_created{job=~\"$job\", instance=~\"$instance:9184\"}[5m]))",
     "legendFormat": "checkpoint execution backlog"
    },
    {
     "expr": "sum(rate(consensus_proposed_blocks{job=~\"$job\", instance=~\"$instance:9184\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Rounds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "current_round{network=\"$network\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "highest_processed_round{network=\"$network\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "consensus_last_committed_leader_round{network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Committed Round",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "last_committed_round{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Finalized TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "(rate(num_shared_obj_tx{job=~\"$job\", instance=~\"$instance:9184\"}[2m]))",
     "legendFormat": "{{host}} shared_object"
    },
    {
     "expr": " (rate(total_transaction_certificates{job=~\"$job\", instance=~\"$instance:9184\"}[2m])) - (rate(num_shared_obj_tx{job=~\"$job\", instance=~\"$instance:9184\"}[2m]))",
     "legendFormat": "{{host}} owned_object"
    }
   ]
  },
  {
   "title": "Certificate Processing Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "(rate(validator_service_handle_certificate_non_consensus_latency_sum{job=~\"$job\", instance=~\"$instance:9184\"}[5m])) / (rate(validator_service_handle_certificate_non_consensus_latency_count{job=~\"$job\", instance=~\"$instance:9184\"}[2m]))",
     "legendFormat": "{{host}} owned_object"
    },
    {
     "expr": "(rate(validator_service_handle_certificate_consensus_latency_sum{job=~\"$job\", instance=~\"$instance:9184\"}[5m])) / (rate(validator_service_handle_certificate_consensus_latency_count{job=~\"$job\", instance=~\"$instance:9184\"}[2m]))",
     "legendFormat": "{{host}} shared_object"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Sui Network Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "(sui_network_peers{job=~\"$job\", instance=~\"$instance:9184\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Primary Network Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "primary_network_peers{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Worker Network Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "worker_network_peers{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Additional Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Inbound Requests Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "rate(sui_inbound_request_latency_sum{job=~\"$job\", instance=~\"$instance:9184\"}[1m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Inbound Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 104 },
   "targets": [
    {
     "expr": "sui_inbound_requests{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Sync Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clamp_min(highest_synced_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"} - highest_known_checkpoint{job=~\"$job\", instance=~\"$instance:9184\"}, 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "sui_outbound_requests{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Outbound Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 113 },
   "targets": [
    {
     "expr": "rate(sui_outbound_request_latency_sum{job=~\"$job\", instance=~\"$instance:9184\"}[1m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Outbound Req. Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 113 },
   "targets": [
    {
     "expr": "sui_outbound_request_errors{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Sequencing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "sequencing_certificate_success{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "sequencing_certificate_failures{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "sequencing_certificate_inflight{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "sequencing_certificate_attempt{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Enqueued Certs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 122 },
   "targets": [
    {
     "expr": "transaction_manager_num_enqueued_certificates{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Voting Right",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 122 },
   "targets": [
    {
     "expr": "current_voting_right{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "User Key Comparison",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "user_key_comparison_count{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{cf_name}}"
    }
   ]
  },
  {
   "title": "Tallying Scores by validator",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 130 },
   "targets": [
    {
     "expr": "tallying_rule_scores{job=~\"$job\", instance=~\"$instance:9184\"}",
     "legendFormat": "{{validator}}"
    }
   ]
  }
 ]
}