{
 "title": "API",
 "tags": [
  "aptos-core",
  "template"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "status", "query": { "query": "label_values(status)" } },
   { "name": "operation_id", "label": "API", "query": { "query": "label_values(operation_id)" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests By Response Status Code",
   "type": "timeseries",
   "description": "All requests processed per second, including bad requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status) (rate(aptos_api_response_status_count{status=~\"$status\"}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests by Endpoint",
   "type": "timeseries",
   "description": "Request count by endpoint per $interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(aptos_api_requests_count{status=~\"$status\"}[$interval]))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "Latency grouped by method",
   "type": "timeseries",
   "description": "Aggregated endpoints latency per $interval, can be filtered by $endpoint",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "repeat": "Datasource",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (method, le) (rate(aptos_api_requests_bucket{method=\"GET\"}[$interval])))",
     "legendFormat": "{{method}}-p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (method, le) (rate(aptos_api_requests_bucket{method=\"GET\"}[$interval])))",
     "legendFormat": "{{method}}-p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (method, le) (rate(aptos_api_requests_bucket{method=\"GET\"}[$interval])))",
     "legendFormat": "{{method}}-p99"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (method, le) (rate(aptos_api_requests_bucket{method=\"POST\"}[$interval])))",
     "legendFormat": "{{method}}-p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (method, le) (rate(aptos_api_requests_bucket{method=\"POST\"}[$interval])))",
     "legendFormat": "{{method}}-p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (method, le) (rate(aptos_api_requests_bucket{method=\"POST\"}[$interval])))",
     "legendFormat": "{{method}}-p99"
    }
   ]
  },
  {
   "title": "Counts by method",
   "type": "timeseries",
   "description": "Aggregated endpoints latency per $interval, can be filtered by $endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{method=\"GET\"}[$interval]))",
     "legendFormat": "{{method}}-Total"
    },
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{method=\"POST\"}[$interval]))",
     "legendFormat": "{{method}}-Total"
    },
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{method=\"GET\", status=~\"2.*\"}[$interval]))",
     "legendFormat": "{{method}}-200s"
    },
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{method=\"POST\", status=~\"2.*\"}[$interval]))",
     "legendFormat": "{{method}}-200s"
    },
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{method=\"GET\", status=~\"4.*\"}[$interval]))",
     "legendFormat": "{{method}}-400s"
    },
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{method=\"POST\", status=~\"4.*\"}[$interval]))",
     "legendFormat": "{{method}}-400s"
    },
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{method=\"GET\", status=~\"5.*\"}[$interval]))",
     "legendFormat": "{{method}}-500s"
    },
    {
     "expr": "sum by (method, le) (rate(aptos_api_requests_count{method=\"POST\", status=~\"5.*\"}[$interval]))",
     "legendFormat": "{{method}}-500s"
    }
   ]
  },
  {
   "title": "Server Internal Errors",
   "type": "timeseries",
   "description": "Server Internal Errors (response code 500) while processing requests, grouped by endpoints",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(aptos_api_requests_count{status=\"500\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "500s over number of requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(aptos_api_requests_count{status=\"500\"}[$interval])) / sum by (operation_id) (rate(aptos_api_requests_count[$interval]))"
    }
   ]
  },
  { "title": "Per API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "$operation_id Latency",
   "type": "timeseries",
   "description": "Aggregated endpoints latency per $interval, can be filtered by $endpoint",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "repeat": "operation_id",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (operation_id, le) (rate(aptos_api_requests_bucket{operation_id=~\"$operation_id\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (operation_id, le) (rate(aptos_api_requests_bucket{operation_id=~\"$operation_id\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (operation_id, le) (rate(aptos_api_requests_bucket{operation_id=~\"$operation_id\"}[$interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "$operation_id Call Volume",
   "type": "timeseries",
   "description": "Aggregated endpoints call volume per $interval, can be filtered by $endpoint",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "repeat": "operation_id",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (operation_id, le) (rate(aptos_api_requests_count{operation_id=~\"$operation_id\"}[$interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by (operation_id, le) (rate(aptos_api_requests_count{operation_id=~\"$operation_id\", status=~\"2.*\"}[$interval]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum by (operation_id, le) (rate(aptos_api_requests_count{operation_id=~\"$operation_id\", status!~\"2.*\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  }
 ]
}