{
 "title": "Execution",
 "tags": [
  "aptos-core",
  "template"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{}, kubernetes_pod_name)"
    }
   },
   { "name": "role", "query": { "query": "label_values(role)" } },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_executor_other_timers_seconds_sum{}[1m]) / rate(aptos_executor_other_timers_seconds_count{}[1m])",
     "legendFormat": "{{name}} {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(aptos_executor_vm_execute_block_seconds_sum{}[1m]) / rate(aptos_executor_vm_execute_block_seconds_count{}[1m])",
     "legendFormat": "_vm_execute {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(aptos_executor_execute_block_seconds_sum{}[1m]) / rate(aptos_executor_execute_block_seconds_count{}[1m])",
     "legendFormat": "_execute_block {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(aptos_executor_commit_blocks_seconds_sum{}[1m]) / rate(aptos_executor_commit_blocks_seconds_count{}[1m])",
     "legendFormat": "_commit_block {{kubernetes_pod_name}}"
    },
    {
     "expr": "(rate(aptos_executor_execute_block_seconds_sum{}[1m]) - rate(aptos_executor_vm_execute_block_seconds_sum{}[1m]) )/ rate(aptos_executor_vm_execute_block_seconds_count{}[1m])",
     "legendFormat": "_non_vm_execute {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Block execution time breakdown per second",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(consensus_duration_sum{}[$interval]) )",
     "legendFormat": "block_execution_time"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_vm_execute_block_seconds_sum{}[$interval]) )",
     "legendFormat": "vm_execute"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_other_timers_seconds_sum{}[$interval]) )",
     "legendFormat": "apply_to_ledger"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_other_timers_seconds_sum{}[$interval]) )",
     "legendFormat": "as_state_compute_result"
    }
   ]
  },
  {
   "title": "Storage read breakdown for execution per second",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_storage_interface_timer_seconds_sum{}[$interval]) )",
     "legendFormat": "wait_for_proof"
    },
    {
     "expr": "quantile(0.67, rate(aptos_storage_interface_timer_seconds_sum{}[$interval]) /  avg(block_executor_concurrency{}))",
     "legendFormat": "async_proof_fetcher_fetch"
    },
    {
     "expr": "quantile(0.67, rate(aptos_storage_interface_timer_seconds_sum{}[$interval]) /  avg(block_executor_concurrency{}) )",
     "legendFormat": "cached_view_get_state_value"
    }
   ]
  },
  {
   "title": "BlockSTM  time breakdown per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_executor_vm_execute_block_seconds_sum{}[$interval]) )",
     "legendFormat": "vm_execution_time"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_dependency_wait_sum{}[$interval]) / avg(block_executor_concurrency{}) ) ",
     "legendFormat": "executor_dependency_wait"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_vm_init_seconds_sum{}[$interval]) / avg(block_executor_concurrency{}) ) ",
     "legendFormat": "vm_init"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_task_validate_seconds_sum{}[$interval]) / avg(block_executor_concurrency{}) ) ",
     "legendFormat": "task_validate"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_task_execute_seconds_sum{}[$interval]) / avg(block_executor_concurrency{}) ) ",
     "legendFormat": "task_execute"
    },
    {
     "expr": "quantile(0.67, rate(block_executor_signature_verification_seconds_sum{}[$interval])) ",
     "legendFormat": "signature_verification"
    }
   ]
  },
  {
   "title": "Block execution time breakdown (per block)",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(consensus_duration_sum{}[$interval])) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "block_execution_time"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_vm_execute_block_seconds_sum{}[$interval])) / quantile(0.67, rate(consensus_duration_count{}[$interval]))",
     "legendFormat": "vm_execute"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_other_timers_seconds_sum{}[$interval])) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "apply_to_ledger"
    },
    {
     "expr": "quantile(0.67, rate(aptos_executor_other_timers_seconds_sum{}[$interval]) ) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "as_state_compute_result"
    }
   ]
  },
  {
   "title": "Storage read breakdown for execution per block",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_storage_interface_timer_seconds_sum{}[$interval]) ) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "wait_for_proof"
    },
    {
     "expr": "quantile(0.67, rate(aptos_storage_interface_timer_seconds_sum{}[$interval]) /  avg(block_executor_concurrency{})) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "async_proof_fetcher_fetch"
    },
    {
     "expr": "quantile(0.67, rate(aptos_storage_interface_timer_seconds_sum{}[$interval]) /  avg(block_executor_concurrency{}) ) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "cached_view_get_state_value"
    },
    {
     "expr": "quantile(0.67, rate(aptos_storage_interface_timer_seconds_sum{}[$interval]) /  avg(block_executor_concurrency{})) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "schedule_proof_read"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_get_state_val_sum{}[$interval]) /  avg(block_executor_concurrency{})) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "versioned_view_get_state_val"
    }
   ]
  },
  {
   "title": "BlockSTM  time breakdown per block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_executor_vm_execute_block_seconds_sum{}[$interval]) ) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "vm_execution_time"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_dependency_wait_sum{}[$interval]) / avg(block_executor_concurrency{}) ) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "executor_dependency_wait"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_vm_init_seconds_sum{}[$interval]) / avg(block_executor_concurrency{}) ) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "vm_init"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_task_validate_seconds_sum{}[$interval]) / avg(block_executor_concurrency{}) ) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "task_validate"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_task_execute_seconds_sum{}[$interval]) / avg(block_executor_concurrency{}) ) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "task_execute"
    },
    {
     "expr": "quantile(0.67, rate(block_executor_signature_verification_seconds_sum{}[$interval])) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "signature_verification"
    },
    {
     "expr": "quantile(0.67, rate(aptos_vm_txn_total_seconds_sum{}[$interval]) / avg(block_executor_concurrency{}) ) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "vm_execute_user_txn"
    }
   ]
  },
  {
   "title": "BlockSTM  operations per block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "quantile(0.67, rate(aptos_execution_dependency_wait_count{}[$interval]) ) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "dependency_wait_per_block"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_task_validate_seconds_count{}[$interval])) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "task_validate_per_block"
    },
    {
     "expr": "quantile(0.67, rate(aptos_execution_task_execute_seconds_count{}[$interval]) ) / quantile(0.67, rate(consensus_duration_count{}[$interval]) )",
     "legendFormat": "task_execute_per_block"
    },
    {
     "expr": "quantile(0.67, rate(aptos_consensus_num_txns_per_block_sum{}[$interval]) / rate(aptos_consensus_num_txns_per_block_count{}[$interval]))",
     "legendFormat": "transactions_per_block"
    }
   ]
  },
  {
   "title": "BlockSTM  concurrency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(block_executor_concurrency{})",
     "legendFormat": "dependency_wait_per_block"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block execution time [p50]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_execute_block_seconds_bucket{}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block execution time [p90]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(aptos_executor_execute_block_seconds_bucket{}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block execution time [p99]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_execute_block_seconds_bucket{}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Time spent in storage to save transactions [p50]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent for persisting execution result to storage when committing blocks",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_save_transactions_seconds_bucket{}[$interval])) by (kubernetes_pod_name, role,le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Time spent in storage to save transactions [p90]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent for persisting execution result to storage when committing blocks",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(aptos_executor_save_transactions_seconds_bucket{}[$interval])) by (kubernetes_pod_name, role,le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Time spent in storage to save transactions [p99]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent for persisting execution result to storage when committing blocks",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_save_transactions_seconds_bucket{}[$interval])) by (kubernetes_pod_name, role,le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "VM execute block time [p50]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block in VM",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_vm_execute_block_seconds_bucket{}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "VM execute block time [p90]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block in VM",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(aptos_executor_vm_execute_block_seconds_bucket{}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "VM execute block time [p99]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block in VM",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_vm_execute_block_seconds_bucket{}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Total time to commit blocks [p50]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to commit blocks",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_commit_blocks_seconds_bucket{}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Total time to commit blocks [p90]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to commit blocks",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(aptos_executor_commit_blocks_seconds_bucket{}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Total time to commit blocks [p99]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to commit blocks",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_commit_blocks_seconds_bucket{}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg Block execution time",
   "type": "graph",
   "description": "The average time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_executor_execute_block_seconds_sum{}[$interval]) / rate(aptos_executor_execute_block_seconds_count{}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg  VM execute block time",
   "type": "graph",
   "description": "The average time spent to execute a block in VM",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_executor_vm_execute_block_seconds_sum{}[$interval]) / rate(aptos_executor_vm_execute_block_seconds_count{}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg  Total time to commit blocks",
   "type": "graph",
   "description": "The average time spent to commit blocks",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_executor_commit_blocks_seconds_sum{}[$interval]) / rate(aptos_executor_commit_blocks_seconds_count{}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg  Time spent in storage to save transactions",
   "type": "graph",
   "description": "The average time spent for persisting execution result to storage when committing blocks",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_executor_save_transactions_seconds_sum{}[$interval]) / rate(aptos_executor_save_transactions_seconds_count{}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg Execute and commit chunk time",
   "type": "graph",
   "description": "The average time spent for executing and committing each chunk in state-syncing",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_executor_execute_and_commit_chunk_seconds_sum{}[$interval]) / rate(aptos_executor_execute_and_commit_chunk_seconds_count{}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Executor Error Counter",
   "type": "graph",
   "description": "The counter that indicates the number of errors reported.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aptos_executor_error_total{}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Execution speculative abort rate",
   "type": "graph",
   "description": "The rate of speculative ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "none", "label": "aborts / s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_execution_speculative_abort_count{}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  }
 ]
}