{
 "title": "SUI Fullnode Monitor Dashboard",
 "description": "the monitor dashboard for SUI fullnode",
 "tags": [
  "sui",
  "fullnode",
  "template"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "network", "query": "devnet,testnet" },
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "interval", "label": "interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(node_uname_info{instance=~\"$instance:9100\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network State Overview For $network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Latest Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "result", "text": "result", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\n| jsonata \"result.epoch\"",
     "url": "https://fullnode.${network}.sui.io",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \"jsonrpc\":\"2.0\", \"method\":\"sui_getSuiSystemState\",\"id\":1}",
      "headers": [],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Latest Checkpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "result", "text": "result", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\n| jsonata \"result\"",
     "url": "https://fullnode.${network}.sui.io",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \"jsonrpc\":\"2.0\", \"method\":\"sui_getLatestCheckpointSequenceNumber\",\"id\":1}",
      "headers": [],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Latest Transaction",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "result", "text": "result", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\n| jsonata \"result\"",
     "url": "https://fullnode.${network}.sui.io",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \"jsonrpc\":\"2.0\", \"method\":\"sui_getTotalTransactionNumber\",\"id\":1}",
      "headers": [],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Validator Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "result", "text": "result", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\n| jsonata \"$count(result.validators.active_validators)\"",
     "url": "https://fullnode.${network}.sui.io",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \"jsonrpc\":\"2.0\", \"method\":\"sui_getSuiSystemState\",\"id\":1}",
      "headers": [],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Total Staked Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "result", "text": "result", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\n| jsonata \"(result.validators.validator_stake+result.validators.delegation_stake)/1000000000\"",
     "url": "https://fullnode.${network}.sui.io",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \"jsonrpc\":\"2.0\", \"method\":\"sui_getSuiSystemState\",\"id\":1}",
      "headers": [],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Reference Gas Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "result", "text": "result", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\n| jsonata \"result\"",
     "url": "https://fullnode.${network}.sui.io",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \"jsonrpc\":\"2.0\", \"method\":\"sui_getReferenceGasPrice\",\"id\":1}",
      "headers": [],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Current Epoch Start At",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "source": "url",
     "type": "uql",
     "uql": "parse-json\n| jsonata \"result.epoch_start_timestamp_ms\"",
     "url": "https://fullnode.${network}.sui.io",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n    \"jsonrpc\": \"2.0\",\n    \"method\": \"sui_getSuiSystemState\",\n    \"id\": 1\n}",
      "method": "POST"
     }
    }
   ]
  },
  { "title": "Node Metrics Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Synced Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "current_epoch{instance=\"$instance:9184\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest Known Checkpoint",
   "type": "stat",
   "description": "The height checkpoint in network as this node known",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "highest_known_checkpoint{instance=\"$instance:9184\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synced Checkpoint",
   "type": "stat",
   "description": "The checkpoint height current synced",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "highest_synced_checkpoint{instance=\"$instance:9184\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synced Transaction",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "total_transaction_certificates{instance=\"$instance:9184\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkpoint Delay",
   "type": "stat",
   "description": "The delay checkpoint height between network and this node ",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(highest_known_checkpoint{instance=\"$instance:9184\"} - highest_synced_checkpoint{instance=\"$instance:9184\"}, 0)",
     "legendFormat": "Last 5m"
    }
   ]
  },
  {
   "title": "Sync TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(total_transaction_certificates{instance=\"$instance:9184\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RPC Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(req_latency_by_route_count{instance=\"$instance:9184\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(req_latency_by_route_sum{instance=\"$instance:9184\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest Checkpoint Discover",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(highest_known_checkpoint{instance=\"$instance:9184\"}[3m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "rate(total_transaction_certificates{instance=\"$instance:9184\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkpoint Sync Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clamp_min(highest_known_checkpoint{instance=\"$instance:9184\"} - highest_synced_checkpoint{instance=\"$instance:9184\"}, 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sui_inbound_request_latency_sum{instance=\"$instance:9184\"}[1m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Outbound Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sui_outbound_request_latency_sum{instance=\"$instance:9184\"}[1m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Machine Information For $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance:.*\"} / 16",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Available",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{instance=~\"$instance:.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$instance:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$instance:.*\"} - node_memory_SwapFree_bytes{instance=~\"$instance:.*\"}) / (node_memory_SwapTotal_bytes{instance=~\"$instance:.*\"} )) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Available ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{instance=~\"$instance:.*\", device=\"/dev/nvme1n1p1\"} / node_filesystem_size_bytes{instance=~\"$instance:.*\", device=\"/dev/nvme1n1p1\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO Waiting [ms]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{instance=~\"$instance:.*\"}[1m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine Hostname",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 31 },
   "options": {
    "content": "<div width=\"100%\" style=\"margin-top:15px;text-align: center;\">\n  <span style=\"font-size: 20px;\"><strong>${hostname}</strong></span>\n</div>"
   }
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$instance:.*\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$instance:.*\"} - node_boot_time_seconds{instance=~\"$instance:.*\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:.*\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance:.*\"}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$instance:.*\"}[5m])) * 100",
     "legendFormat": "System Uasge"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$instance:.*\"}[5m])) * 100",
     "legendFormat": "User Uasge"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",instance=~\"$instance:.*\"}[5m])) * 100",
     "legendFormat": "IOwait Uasge"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$instance:.*\"}[5m])) * 100",
     "legendFormat": "IRQs Uasge"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\"nice|steal\",instance=~\"$instance:.*\"}[5m])) * 100",
     "legendFormat": "Other Uasge"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:.*\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:.*\"} - node_memory_MemFree_bytes{instance=~\"$instance:.*\"} - (node_memory_Cached_bytes{instance=~\"$instance:.*\"} + node_memory_Buffers_bytes{instance=~\"$instance:.*\"})",
     "legendFormat": "RAM Actual Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance:.*\"} + node_memory_Buffers_bytes{instance=~\"$instance:.*\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance:.*\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$instance:.*\"} - node_memory_SwapFree_bytes{instance=~\"$instance:.*\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance:.*\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance:.*\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~\"$instance:.*\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~\"$instance:.*\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance:.*\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance:.*\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$instance:.*\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$instance:.*\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "description": "The number of kibibytes read and written to the device  per second",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device!~\"md.*\",instance=~\"$instance:.*\"}[$interval])",
     "legendFormat": "{{device}} Read"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{device!~\"md.*\",instance=~\"$instance:.*\"}[$interval])",
     "legendFormat": "{{device}} Write"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance:.*\"}[$interval])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance:.*\"}[$interval])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  }
 ]
}