{
 "title": "Sui Validator Dashboard Testnet Wave 3",
 "tags": [ "template" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "INPUT_OBJECTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_input_objects_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TOTAL_CERTIFICATE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "total_transaction_certificates", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FULLNODE_TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(total_transaction_certificates[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TXNS_EFFECTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_transaction_effects", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HIGHEST_CHECKPOINT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "highest_known_checkpoint", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SYNCED_CHECKPOINT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "highest_synced_checkpoint", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CHECKPOINT_DELAY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "write_delay_nanos", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "[Fullnode]RPC.DISCOVER",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "req_latency_by_route_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "[Fullnode]REQ.LATENCY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "req_latency_by_route_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RUNNING_TIME [days]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_time_seconds - process_start_time_seconds{chain=\"SUI\"}) / 3600 /24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SYNC_THROUGHPUT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(total_transaction_certificates[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHECKPOINT_SYNC_PROGRESS",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 4, "x": 10, "y": 4 },
   "targets": [
    { "expr": "highest_synced_checkpoint", "legendFormat": "__auto" },
    { "expr": "highest_known_checkpoint", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SYNC_LAG",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clamp_min(highest_synced_checkpoint - on(instance, job) highest_known_checkpoint, 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "INBOUND_LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(sui_inbound_request_latency_sum[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OUTBOUND_LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 13 },
   "targets": [
    {
     "expr": "rate(sui_outbound_request_latency_sum[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU_LOAD",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{job=~\"sui-testnet\"} / 16",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM_AVAILABLE [GB]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=~\"sui-testnet\"} / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK_AVAILABLE [GB]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=~\"sui-testnet\", instance=~\"sui-testnet.nodeinfravalidators.com:9100\", mountpoint=~\"/\"} / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK_IO_WAITING [ms]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{job=~\"sui-testnet\"}[1m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK_READ_TIME [ms]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{job=~\"sui-testnet\"}[1m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK_WRITE_TIME [ms]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{job=~\"sui-testnet\"}[1m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reference Gas Price & Nodeinfra",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "Sui_NextEpochGasPrice{name=\"nodeinfra\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "bottomk(1, topk(14, Sui_NextEpochGasPrice))",
     "legendFormat": "Reference Gas Price (#14)"
    }
   ]
  },
  {
   "title": "All Gas Prices",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sort(Sui_NextEpochGasPrice)", "legendFormat": "{{name}}" },
    {
     "expr": "bottomk(1, topk(14, Sui_NextEpochGasPrice))",
     "legendFormat": "Reference Gas Price"
    }
   ]
  },
  {
   "title": "nodeinfra GasPrice",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Sui_NextEpochGasPrice{address=~\"0x409d52befdeeae83bd669236850a159d6d231c9a\", instance=~\"15.235.85.218:8080\", job=~\"Sui-validator-game\", name=~\"nodeinfra\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}