{
 "title": "Geth Server",
 "description": "Monitor your Ethereum Geth server with Prometheus and Grafana.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(up{job=~\"int-test\"}, job)"
    }
   },
   {
    "name": "purpose",
    "query": {
     "query": "label_values(up{purpose=~\"geth.*\"}, purpose)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geth_block{purpose=\"$purpose\"}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "geth_block_transactions{purpose=\"$purpose\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Ether Transfers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "geth_eth_transfers{purpose=\"$purpose\"}",
     "legendFormat": "ETH"
    },
    {
     "expr": "geth_token_transfers{purpose=\"$purpose\"}",
     "legendFormat": "Tokens"
    }
   ]
  },
  {
   "title": "ETH Value",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geth_block_value{purpose=\"$purpose\"}"
    }
   ]
  },
  {
   "title": "Since Last Block",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geth_seconds_last_block{purpose=\"$purpose\"}"
    }
   ]
  },
  {
   "title": "ETH Transfers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "geth_eth_transfers{purpose=\"$purpose\"}",
     "legendFormat": "ETH Transfers"
    }
   ]
  },
  {
   "title": "ETH Transfers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geth_eth_transfers{purpose=\"$purpose\"}"
    }
   ]
  },
  {
   "title": "Token Transfers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geth_token_transfers{purpose=\"$purpose\"}"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geth_pending_transactions{purpose=\"$purpose\"}"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "geth_block_size_bytes{purpose=\"$purpose\"}",
     "legendFormat": "Token Transfers"
    }
   ]
  },
  {
   "title": "Gas Price (gwei)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_gas_price{purpose=\"$purpose\"} / 1000000000",
     "legendFormat": "Gas Price"
    }
   ]
  },
  {
   "title": "Gas Price",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geth_gas_price{purpose=\"$purpose\"} / 1000000000"
    }
   ]
  },
  {
   "title": "Block Difficulty",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "geth_block_difficulty{purpose=\"$purpose\"} / 10000000000000",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Block Nonce",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 13 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "geth_block_nonce{purpose=\"$purpose\"} / 1000000000000000000",
     "legendFormat": "Nonce"
    }
   ]
  },
  {
   "title": "Gas Used",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_gas_used{purpose=\"$purpose\"}",
     "legendFormat": "Token Transfers"
    }
   ]
  },
  {
   "title": "Contracts Created",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "geth_contracts_created{purpose=\"$purpose\"}",
     "legendFormat": "Contracts"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geth_load_time{purpose=\"$purpose\"}"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "geth_pending_transactions{purpose=\"$purpose\"}",
     "legendFormat": "transactions"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "content": "<p align=\"center\" style=\"font-size:30pt\">Today Totals</p>",
   "targets": [
    {}
   ]
  },
  {
   "title": "Today's Sent ETH",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(geth_block_value{purpose=\"$purpose\"})"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 28 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "geth_block_transactions{purpose=\"$purpose\"}",
     "legendFormat": "Transactions"
    }
   ]
  }
 ]
}