{
 "title": "Metapixel Log",
 "description": "Loki v2+ showcase using JSON NGINX access logs.",
 "tags": [ "legacy" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "label_values({chain=\"APT\"}, chain)"
   },
   {
    "name": "network",
    "query": "label_values({chain=~\"$chain\"},network)"
   },
   {
    "name": "region",
    "query": "label_values({chain=~\"$chain\", network=~\"$network\"}, region)"
   },
   {
    "name": "job",
    "query": "label_values({chain=~\"$chain\", network=~\"$network\", region=~\"$region\"}, job)"
   },
   { "name": "filename", "query": "label_values(filename)" }
  ]
 },
 "panels": [
  {
   "title": "KPI's",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total requests per second ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" |  __error__=\"\" [1m])",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "NGINX logs in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"}[$__interval])",
     "legendFormat": "{{servicetype}} {{region}}"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json |apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" |  unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} |= \"Googlebot\" | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\")[$__interval])) / (sum(count_over_time(({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} != \"Googlebot\" | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\")[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Realtime visitors ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "# NGINX log lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\"[$__interval]))"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | status >= 500 |__error__=\"\"[$__interval])) / (sum(count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | __error__=\"\"[$__interval]))/ 100)"
    }
   ]
  },
  {
   "title": "Requests per Country",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (geoip_country_code) (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | geoip_country_code != \"\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Top Countries",
   "type": "table",
   "gridPos": { "h": 11, "w": 3, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, sum by (geoip_country_code) (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | geoip_country_code != \"\" and  __error__=\"\" [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "{chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | line_format \"{{.msec}} | {{.status}} apikey={{.apikey}}\\n request body: {{.request_body}}\" | __error__=\"\"",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Request statistics over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Time Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.50,{chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | unwrap request_time |  __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "quantile_over_time(0.95,{chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | unwrap request_time |  __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by (host) (max_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | unwrap request_time |  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP status codes over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Acquisition and Behaviour",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 API key",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "topk(10, sum by (apikey) (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | status=200 |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top 10 visitor IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_addr) (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top 10 User Agents",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_user_agent) (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top 10 Requested Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "topk(10, sum by (request_uri) (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml` | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" |status = 200 and request_uri != \"/\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top 10 Function",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 39 },
   "targets": [
    {
     "expr": "topk(10, sum by (function) (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | line_format \"{{.request_body}}\" | json | __error__=\"\" | line_format \"{\\\"function\\\": \\\"{{.function}}\\\"}\" | json [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top 10 IP, Function",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_addr, function) (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | line_format \"{{.request_body}}, \\\"remote_addr\\\" : \\\"{{.remote_addr}}\\\"\" | json | __error__=\"\"[$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top 10 API key, Function",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "topk(10, sum by (apikey, function) (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | line_format \"{{.request_body}}, \\\"apikey\\\" : \\\"{{.apikey}}\\\"\" | json | status=200 | __error__=\"\"[$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top 10 API key, IP, Function",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_addr, apikey, function) (count_over_time({chain=~\"$chain\", network=~\"$network\", region=~\"$region\", job=~\"$job\", filename=~\"$filename\"} | json | apikey=\"2oeoqU3ocvjXdEmjkssy9PlMjSP94puD\" | line_format \"{{.request_body}}, \\\"apikey\\\" : \\\"{{.apikey}}\\\", \\\"ip\\\": \\\"{{.remote_addr}}\\\"\" | json | status=200 | __error__=\"\"[$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  }
 ]
}