{
 "title": "Nine Chronicles Headless",
 "tags": [ "legacy" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values({job=~\"ext-prod-planetarium-ninechronicles-mainnet\"},job)"
    }
   },
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, network)"
    }
   },
   {
    "name": "nodetype",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", nodetype=\"headless\"}, nodetype)"
    }
   },
   {
    "name": "nodename",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$instance:9100\"}, nodename)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\",nodetype=~\"$nodetype\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "nodeID",
    "label": "nodeID",
    "query": {
     "query": "label_values(aptos_connections{direction=\"inbound\"},peer_id)"
    }
   },
   {
    "name": "chainAPI",
    "query": {
     "query": "CollectionLookup(mainnet,mainnet.aptoslabs.com,llt,testnet.aptoslabs.com,$chain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "9c Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Diff between Miner Tip and Node Tip",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "NineChronicles_Miner_Blocktip{job='ext-prod-planetarium-ninechronicles-mainnet'} - ignoring(instance, node) NineChronicles_Blockheight{node=\"http://fra-nc-1.ninodes.com\"}",
     "legendFormat": "Frankfurt"
    },
    {
     "expr": "NineChronicles_Miner_Blocktip{job='ext-prod-planetarium-ninechronicles-mainnet'} - ignoring(instance, node) NineChronicles_Blockheight{node=\"http://la-nc-1.ninodes.com\"}",
     "legendFormat": "LA"
    },
    {
     "expr": "NineChronicles_Miner_Blocktip{job='ext-prod-planetarium-ninechronicles-mainnet'} - ignoring(instance, node) NineChronicles_Blockheight{node=\"http://nj-nc-1.ninodes.com\"}",
     "legendFormat": "New Jersey"
    },
    {
     "expr": "NineChronicles_Miner_Blocktip{job='ext-prod-planetarium-ninechronicles-mainnet'} - ignoring(instance, node) NineChronicles_Blockheight{node=\"http://sgp-nc-1.ninodes.com\"}",
     "legendFormat": "Singapore"
    },
    {
     "expr": "NineChronicles_Miner_Blocktip{job='ext-prod-planetarium-ninechronicles-mainnet'} - ignoring(instance, node) NineChronicles_Blockheight{node=\"http://backup-nc-1.ninodes.com\"}",
     "legendFormat": "Backup"
    },
    {
     "expr": "NineChronicles_Miner_Blocktip{job='ext-prod-planetarium-ninechronicles-mainnet'} - ignoring(instance, node) NineChronicles_Blockheight{node=\"http://tky-nc-1.ninodes.com\"}",
     "legendFormat": "Tokyo"
    }
   ]
  },
  { "title": "All Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Hardware Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\"} - 0"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\"}) by (instance)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\"} - 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\"}) by (instance) /8",
     "legendFormat": "Cores"
    },
    {
     "expr": "node_load5{job=~\"$job\"}",
     "legendFormat": "5m load"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[$__interval])) by (instance)) * 100",
     "legendFormat": "CPU used%"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"}))) * 100",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=~\"$job\"}[$__interval])) by (instance)",
     "legendFormat": "Disk read%"
    },
    {
     "expr": "100 - (sum(node_filesystem_avail_bytes{job=~\"$job\",mountpoint=~\"/\",fstype=~\"ext.?|xfs\"}/node_filesystem_size_bytes{job=~\"$job\",mountpoint=~\"/\",fstype=~\"ext.?|xfs\"}) by (instance)) * 100",
     "legendFormat": "/ used%"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"$job\"}[$__interval])) by (instance)",
     "legendFormat": "Disk write%"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=~\"$job\"}[$__interval])*8) by (instance)",
     "legendFormat": "Download"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=~\"$job\"}[$__interval])*8) by (instance)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Blockheight & StagedTx Changes",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "NineChronicles_Blockheight", "legendFormat": "Verbose" },
    {
     "expr": "increase(NineChronicles_Blockheight[2m])",
     "legendFormat": "Blockheight Increase"
    },
    {
     "expr": "rate(NineChronicles_StagedTxs[1m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Blockheight",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "NineChronicles_Blockheight{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://fra-nc-1.ninodes.com\"}",
     "legendFormat": "Frankfurt"
    },
    {
     "expr": "NineChronicles_Blockheight{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://la-nc-1.ninodes.com\"}",
     "legendFormat": "LA"
    },
    {
     "expr": "NineChronicles_Blockheight{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://nj-nc-1.ninodes.com\"}",
     "legendFormat": "New Jersey"
    },
    {
     "expr": "NineChronicles_Blockheight{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://sgp-nc-1.ninodes.com\"}",
     "legendFormat": "Singapore"
    },
    {
     "expr": "NineChronicles_Blockheight{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://tky-nc-1.ninodes.com\"}",
     "legendFormat": "Tokyo"
    },
    {
     "expr": "NineChronicles_Blockheight{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://backup-nc-1.ninodes.com\"}",
     "legendFormat": "Back-up"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "NineChronicles_Peers{job=\"ext-prod-planetarium-ninechronicles-mainnet\",node=\"http://fra-nc-1.ninodes.com\"}",
     "legendFormat": "Frankfurt"
    },
    {
     "expr": "NineChronicles_Peers{job=\"ext-prod-planetarium-ninechronicles-mainnet\",node=\"http://la-nc-1.ninodes.com\"}",
     "legendFormat": "LA"
    },
    {
     "expr": "NineChronicles_Peers{job=\"ext-prod-planetarium-ninechronicles-mainnet\",node=\"http://nj-nc-1.ninodes.com\"}",
     "legendFormat": "New Jersey"
    },
    {
     "expr": "NineChronicles_Peers{job=\"ext-prod-planetarium-ninechronicles-mainnet\",node=\"http://sgp-nc-1.ninodes.com\"}",
     "legendFormat": "Singapore"
    },
    {
     "expr": "NineChronicles_Peers{job=\"ext-prod-planetarium-ninechronicles-mainnet\",node=\"http://tky-nc-1.ninodes.com\"}",
     "legendFormat": "Tokyo"
    },
    {
     "expr": "NineChronicles_Peers{job=\"ext-prod-planetarium-ninechronicles-mainnet\",node=\"http://backup-nc-1.ninodes.com\"}",
     "legendFormat": "Back-up"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "NineChronicles_Clients{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://fra-nc-1.ninodes.com\"}",
     "legendFormat": "Frankurt"
    },
    {
     "expr": "NineChronicles_Clients{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://la-nc-1.ninodes.com\"}",
     "legendFormat": "LA"
    },
    {
     "expr": "NineChronicles_Clients{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://nj-nc-1.ninodes.com\"}",
     "legendFormat": "New Jersey"
    },
    {
     "expr": "NineChronicles_Clients{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://sgp-nc-1.ninodes.com\"}",
     "legendFormat": "Singapore"
    },
    {
     "expr": "NineChronicles_Clients{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://tky-nc-1.ninodes.com\"}",
     "legendFormat": "Tokyo"
    },
    {
     "expr": "NineChronicles_Clients{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://backup-nc-1.ninodes.com\"}",
     "legendFormat": "Back-up"
    }
   ]
  },
  {
   "title": "Staged Transactions",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "NineChronicles_StagedTxs{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://fra-nc-1.ninodes.com\"}",
     "legendFormat": "Frankfurt"
    },
    {
     "expr": "NineChronicles_StagedTxs{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://la-nc-1.ninodes.com\"}",
     "legendFormat": "LA"
    },
    {
     "expr": "NineChronicles_StagedTxs{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://nj-nc-1.ninodes.com\"}",
     "legendFormat": "New Jersey"
    },
    {
     "expr": "NineChronicles_StagedTxs{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://sgp-nc-1.ninodes.com\"}",
     "legendFormat": "Singapore"
    },
    {
     "expr": "NineChronicles_StagedTxs{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://tky-nc-1.ninodes.com\"}",
     "legendFormat": "Tokyo"
    },
    {
     "expr": "NineChronicles_StagedTxs{job=\"ext-prod-planetarium-ninechronicles-mainnet\", node=\"http://backup-nc-1.ninodes.com\"}",
     "legendFormat": "Back-up"
    }
   ]
  }
 ]
}