{
 "title": "Silicon CDK State DB",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Table",
   "type": "table",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT table_name\nFROM information_schema.tables\nWHERE table_schema = 'state' AND table_type = 'BASE TABLE';\n"
    }
   ]
  },
  {
   "title": "batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "rawSql": "select * from state.batch" }
   ]
  },
  {
   "title": "batch height",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select max(batch_num) from state.batch;"
    }
   ]
  },
  {
   "title": "batch_data_backup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select * from state.batch_data_backup;"
    }
   ]
  },
  {
   "title": "forced_batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "select * from state.forced_batch;"
    }
   ]
  },
  {
   "title": "block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "rawSql": "select * from state.block;" }
   ]
  },
  {
   "title": "fork_id",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "rawSql": "select * from state.fork_id;" }
   ]
  },
  {
   "title": "exit_root",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "rawSql": "select * from state.exit_root;" }
   ]
  },
  {
   "title": "monitored_txs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "select * from state.monitored_txs;"
    }
   ]
  },
  {
   "title": "l2block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "rawSql": "select * from state.l2block;" }
   ]
  },
  {
   "title": "receipt",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "rawSql": "select * from state.receipt;" }
   ]
  },
  {
   "title": "log",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "rawSql": "select * from state.log;" }
   ]
  },
  {
   "title": "sync_info",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "select * from state.sync_info;" }
   ]
  },
  {
   "title": "proof",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    { "rawSql": "select * from state.proof;" }
   ]
  },
  {
   "title": "trusted_reorg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "select * from state.trusted_reorg;"
    }
   ]
  },
  {
   "title": "sequences",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "select * from state.sequences;" }
   ]
  },
  {
   "title": "virtual_batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "rawSql": "select * from state.virtual_batch;"
    }
   ]
  },
  {
   "title": "transaction",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select * from state.transaction;"
    }
   ]
  },
  {
   "title": "verified_batch",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select * from state.verified_batch;"
    }
   ]
  }
 ]
}