{
 "title": "Silicon all dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "all",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "select * from state.batch;" },
    {
     "rawSql": "select * from state.batch_data_backup;"
    },
    { "rawSql": "select * from state.block;" },
    { "rawSql": "select * from state.exit_root;" },
    { "rawSql": "select * from state.fork_id;" },
    { "rawSql": "select * from state.l2block;" },
    {
     "rawSql": "select * from state.monitored_txs;"
    },
    { "rawSql": "select * from state.proof;" },
    { "rawSql": "select * from state.receipt;" },
    { "rawSql": "select * from state.sequences;" },
    { "rawSql": "select * from state.sync_info;" },
    {
     "rawSql": "select * from state.transaction;"
    },
    {
     "rawSql": "select * from state.trusted_reorg;"
    },
    {
     "rawSql": "select * from state.verified_batch;"
    },
    {
     "rawSql": "select * from state.virtual_batch;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "rawSql": "select * from state.log;" },
    {
     "rawSql": "select * from state.forced_batch;"
    }
   ]
  },
  {
   "title": "max batch",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select max(batch_num) as max_batch from state.batch limit 10;"
    },
    {
     "rawSql": "select max(batch_num) as max_verified_batch from state.verified_batch LIMIT 10;"
    },
    {
     "rawSql": "select max(batch_num) as max_virtual_batch from state.virtual_batch LIMIT 10;"
    }
   ]
  },
  {
   "title": "max block",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select max(block_num) as max_block from state.block limit 10;"
    },
    {
     "rawSql": "select max(block_num) as max_l2block from state.l2block limit 10;"
    },
    {
     "rawSql": "select max(block_num) as max_monitored_txs from state.monitored_txs limit 10;"
    },
    {
     "rawSql": "select max(block_num) as max_receipt from state.receipt limit 10;"
    },
    {
     "rawSql": "select max(block_num) as max_verified_batch from state.verified_batch limit 10;"
    },
    {
     "rawSql": "select max(block_num) as max_virtual_batch from state.virtual_batch limit 10;"
    }
   ]
  },
  {
   "title": "Batch value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "Silicon_Batch", "legendFormat": "Silicon Batch" },
    { "expr": "Silicon_Verified_Batch", "legendFormat": "Silicon Verified Batch" },
    { "expr": "Silicon_Virtual_Batch", "legendFormat": "Silicon Virtual Batch" }
   ]
  },
  {
   "title": "Increment of batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "increase(Silicon_Batch[15m])", "legendFormat": "Silicon Batch" },
    {
     "expr": "increase(Silicon_Verified_Batch[1h])",
     "legendFormat": "Silicon Verified Batch"
    },
    {
     "expr": "increase(Silicon_Virtual_Batch[1h])",
     "legendFormat": "Silicon Virtual Batch"
    }
   ]
  }
 ]
}