{
 "title": "Sui Validator",
 "tags": [ "legacy" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\",network=~\"$network\",servicetype=~\"$servicetype\"},job)"
    }
   },
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"SUI\"}, chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(node_uname_info{servicetype=~\"$servicetype\"}, network)"
    }
   },
   {
    "name": "servicetype",
    "query": {
     "query": "label_values(node_uname_info{servicetype=~\"validator\"}, servicetype)"
    }
   },
   {
    "name": "nodename",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$instance:9100\"}, nodename)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\",servicetype=~\"$servicetype\", purpose!~\"update_message\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "nodeID",
    "label": "nodeID",
    "query": {
     "query": "label_values(aptos_connections{direction=\"inbound\"},peer_id)"
    }
   },
   {
    "name": "chainAPI",
    "query": {
     "query": "CollectionLookup(mainnet,mainnet.aptoslabs.com,llt,testnet.aptoslabs.com,$chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "FULLNODE_TPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(total_transaction_certificates{job=~\"$job\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Round",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_round{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Current Round[5min]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(current_round{job=~\"$job\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Executed Checkpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_executed_checkpoint{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Executed Checkpoint Increase",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(last_executed_checkpoint{job=~\"$job\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}