{
 "title": "TIA_Validator_Status",
 "description": "Dashboard Celestia ",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{chain=\"TIA\"},chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\"}, network)"
    }
   },
   {
    "name": "servicetype",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\", servicetype=~\"validator\"}, servicetype)"
    }
   },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\",network=~\"$network\", servicetype=~\"$servicetype\"},job)"
    }
   },
   {
    "name": "nodename",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$instance:9100\"}, nodename)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\",servicetype=~\"$servicetype\", purpose!~\"update_message\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "nodeID",
    "label": "nodeID",
    "query": {
     "query": "label_values(aptos_connections{direction=\"inbound\"},peer_id)"
    }
   },
   {
    "name": "chainAPI",
    "query": {
     "query": "CollectionLookup(mainnet,mainnet.aptoslabs.com,llt,testnet.aptoslabs.com,$chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>Cumulo Dashboard - Celestia Chain</h1>\n<p><a href=\"https://docs.celestia.org\"><img src=\"https://docs.celestia.org/logo-light.svg\" width=\"500px\"/></a></p>\n</center>"
   }
  },
  {
   "title": "Validator health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "options": {
    "content": "\r\n<table style=\"width:100%; height:100%;border:0px solid black;\">\r\n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><center><img width=\"300px\" src=\"https://img.cryptorank.io/coins/celestia1666255234398.png\" /></td>\r\n</table>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{chain=\"$chain\", instance=\"$instance:26660\"}"
    }
   ]
  },
  {
   "title": "Syncing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "cometbft_consensus_state_syncing{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "chain status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Online validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators-cometbft_consensus_missing_validators{chain='$chain'}"
    }
   ]
  },
  {
   "title": "Offline validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Total bonded tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Last signed height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_last_signed_height{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Voting power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Total Tx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "missing validators power",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators_power{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Voting Power offline",
   "type": "stat",
   "description": "% voting power of the missing validators",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cometbft_consensus_missing_validators_power{chain=\"$chain\"} / cometbft_consensus_validators_power{chain=\"$chain\"})"
    }
   ]
  },
  {
   "title": "Unconfirmed Tx",
   "type": "gauge",
   "description": "Number of uncommitted transactions",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Missed Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_missed_blocks{job=~\"$job\",chain=~\"$chain\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Blocks/min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(cometbft_consensus_height{chain=\"$chain\"}[1m]))"
    }
   ]
  },
  {
   "title": "Blocks / min",
   "type": "timeseries",
   "description": "Number of block produced last minute",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(cometbft_consensus_height{chain=\"$chain\", instance=\"$instance:26660\"}[1m])"
    }
   ]
  },
  {
   "title": "Block Size ",
   "type": "timeseries",
   "description": "Block size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{chain=\"$chain\", instance=\"$instance:26660\"}"
    }
   ]
  },
  {
   "title": "Nº validators",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{chain=\"$chain\", instance=\"$instance:26660\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  }
 ]
}