{
 "title": "Aptos_Fullnode_Kong",
 "description": "Dashboard that graphs metrics exported via Prometheus plugin in Kong (http://github.com/kong/kong)",
 "tags": [ "🔶 P2 ✴️" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(kong_nginx_connections_total{chain=~\"APT\"},chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(kong_nginx_connections_total{chain=~\"$chain\"},network)"
    }
   },
   {
    "name": "servicetype",
    "query": {
     "query": "label_values(kong_nginx_connections_total{chain=~\"$chain\",network=~\"$network\"},servicetype)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(kong_nginx_connections_total{chain=~\"$chain\",network=~\"$network\", servicetype=~\"$servicetype\"},region)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kong_nginx_connections_total{chain=~\"$chain\",network=~\"$network\",region=~\"$region\"},instance)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(kong_http_requests_total{chain=~\"$chain\",network=~\"$network\",region=~\"$region\",service!~\"aptos.*\"},service)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(kong_http_requests_total{chain=~\"$chain\",network=~\"$network\",region=~\"$region\",route!~\"aptos.*\"},route)"
    }
   },
   {
    "name": "upstream",
    "query": {
     "query": "label_values(kong_upstream_target_health, upstream)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nginx connection state [ALL]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=~\"active|reading|writing|waiting\", chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}) by (chain, servicetype, network, state)",
     "legendFormat": "{{state}} {{region}}"
    }
   ]
  },
  {
   "title": "Nginx connection state [All]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=~\"active|reading|writing|waiting\", chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}) by (chain, servicetype, network, state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Nginx connection state [$region]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "repeat": "region",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=~\"active|reading|writing|waiting\", chain=~\"APT\", servicetype=~\"$servicetype\", network=~\"$network\", region=~\"$region\", instance=~\"$instance:8001\"}) by (chain, servicetype, network, region, state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Nginx connection state [$region]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "repeat": "region",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=~\"active|reading|writing|waiting\", chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\", region=~\"$region\"}) by (chain, servicetype, network, region, state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total/Handles/Accepted Connections[$region]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "repeat": "region",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=\"total\", chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\", region=~\"$region\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kong_nginx_connections_total{state=\"handled\", chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\", region=~\"$region\"})",
     "legendFormat": "Handled"
    },
    {
     "expr": "sum(kong_nginx_connections_total{state=\"accepted\", chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\", region=~\"$region\"})",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total requests per second (RPS) by Region [200 Status code]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (chain, servicetype, network, region, instance, code) (rate(kong_http_requests_total{chain=\"$chain\", network=\"$network\", code=\"200\"}[1m]))",
     "legendFormat": "{{code}} {{region}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Total requests per second (RPS) by Consumer [200 Status code]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (chain, servicetype, network, consumer, code) (rate(kong_http_requests_total{chain=\"$chain\", network=\"$network\", code=\"200\",}[1m]))",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  {
   "title": "Total requests per second (RPS) by Region, Consumer, Status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (chain, servicetype, network, region, instance, consumer, code) (rate(kong_http_requests_total{chain=\"$chain\", network=\"$network\"}[1m]))",
     "legendFormat": "{{code}} {{region}} {{consumer}} ({{instance}}) "
    }
   ]
  },
  {
   "title": "Total requests per second (RPS) by Region, Status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", service!=\"test\", route=~\"$route\", chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])) by (chain, servicetype, network, region, service,code, instance)",
     "legendFormat": "{{code}} {{region}}({{instance}}) {{consumer}}"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Time per Region",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{service=~\"$service\", service!=\"test\", service!=\"test\",route=~\"$route\",chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])) by (chain, servicetype, network, region, service,le))",
     "legendFormat": "p90-{{region}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{service=~\"$service\", service!=\"test\", service!=\"test\",route=~\"$route\",chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])) by (chain, servicetype, network, region, service,le))",
     "legendFormat": "p95-{{region}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{service=~\"$service\", service!=\"test\", service!=\"test\",route=~\"$route\",chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])) by (chain, servicetype, network, region, service,le))",
     "legendFormat": "p99-{{region}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kong_request_latency_ms_bucket{service=~\"$service\", service!=\"test\", service!=\"test\",route=~\"$route\",chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])) by (chain, servicetype, network, region, service,le))",
     "legendFormat": "p50-{{region}}"
    }
   ]
  },
  {
   "title": "Kong Proxy Latency per Region",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{service=~\"$service\", service!=\"test\", service!=\"test\",route=~\"$route\",chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])) by (chain, servicetype, network, region, service,le))",
     "legendFormat": "p90-{{region}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{service=~\"$service\", service!=\"test\", service!=\"test\",route=~\"$route\",chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])) by (chain, servicetype, network, region, service,le))",
     "legendFormat": "p95-{{region}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{service=~\"$service\", service!=\"test\", service!=\"test\",route=~\"$route\",chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])) by (chain, servicetype, network, region, service,le))",
     "legendFormat": "p99-{{region}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kong_kong_latency_ms_bucket{service=~\"$service\", service!=\"test\", service!=\"test\",route=~\"$route\",chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])) by (chain, servicetype, network, region, service,le))",
     "legendFormat": "p50-{{region}}"
    }
   ]
  },
  {
   "title": "Upstream Time across per Region",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{service=~\"$service\", service!=\"test\", service!=\"test\",route=~\"$route\",chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])) by (chain, servicetype, network, region, service,le))",
     "legendFormat": "p90-{{region}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{service=~\"$service\", service!=\"test\", service!=\"test\",route=~\"$route\",chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])) by (chain, servicetype, network, region, service,le))",
     "legendFormat": "p95-{{region}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{service=~\"$service\", service!=\"test\", service!=\"test\",route=~\"$route\",chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])) by (chain, servicetype, network, region, service,le))",
     "legendFormat": "p99-{{region}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kong_upstream_latency_ms_bucket{service=~\"$service\", service!=\"test\", service!=\"test\",route=~\"$route\",chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])) by (chain, servicetype, network, region, service,le))",
     "legendFormat": "p50-{{region}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Bandwidth (bits/sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])*8) by (chain, servicetype, network, region, type)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Egress per Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{exported_direction=\"egress\", service =~\"$service\",route=~\"$route\",chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\"}[1m])) by (chain, servicetype, network, region, service)",
     "legendFormat": "{{region}} {{service}}"
    }
   ]
  },
  {
   "title": "Ingress per Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{exported_direction=\"ingress\", service =~\"$service\", chain=\"$chain\", servicetype=\"$servicetype\", network=\"$network\"}[1m])) by (chain, servicetype, network, region, service)",
     "legendFormat": "{{region}} {{service}}"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Healthy status",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "sum(kong_upstream_target_health{state=\"healthy\",upstream=~\"$upstream\", chain=\"$chain\", network=\"$network\", servicetype=\"$servicetype\"}) by (chain, servicetype, network, region, upstream,target,address) * -1  + sum(kong_upstream_target_health{state=~\"(unhealthy|dns_error)\",upstream=~\"$upstream\", chain=\"$chain\", network=\"$network\", servicetype=\"$servicetype\"}) by (chain, servicetype, network, region, upstream,target,address)",
     "legendFormat": "{{upstream}}:{{target}}::{{address}}"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "sum(\n# map state to a numeric value\n# since grafana doesn't support value mapping yet\n  label_replace(\n    label_replace(\n      label_replace(\n       kong_upstream_target_health{chain=\"$chain\", network=\"$network\", servicetype=\"$servicetype\",upstream=~\"$upstream\"}\n       # healthy is positive number\n       , \"state_value\", \"1\", \"state\", \"healthy\"\n       # healthchecks_off is 0\n      ), \"state_value\", \"0\", \"state\", \"healthchecks_off\"\n      # unhealthy is negative number\n    ), \"state_value\", \"-1\", \"state\", \"(dns_error|unhealthy)\"\n  )\n)\nby (chain, servicetype, network, region, upstream, target, address, state, state_value) > 0"
    }
   ]
  },
  {
   "title": "Caching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kong shared memory usage by Node [$region]",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 98 },
   "repeat": "region",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kong_memory_lua_shared_dict_bytes{chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\", region=~\"$region\",shared_dict!~\"kong_process_events\"}/kong_memory_lua_shared_dict_total_bytes{chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\", region=~\"$region\",shared_dict!~\"kong_process_events\"})*100",
     "legendFormat": "{{shared_dict}} ({{kong_subsystem}})"
    }
   ]
  },
  {
   "title": "Kong worker Lua VM usage by Node [$region]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 116 },
   "repeat": "region",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kong_memory_workers_lua_vms_bytes{chain=~\"$chain\", servicetype=~\"$servicetype\", network=~\"$network\", region=~\"$region\"}",
     "legendFormat": "PID:{{pid}} ({{kong_subsystem}})"
    }
   ]
  }
 ]
}