{
 "title": "Ethereum_Nethermind_Status",
 "description": "Nethermind Node Monitoring Dashbaord",
 "tags": [
  "Ethereum",
  "Nethermind"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{chain=\"ETH\"}, chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\"}, network)"
    }
   },
   {
    "name": "servicetype",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\"}, servicetype)"
    }
   },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\",network=~\"$network\", servicetype=~\"$servicetype\"},job)"
    }
   },
   {
    "name": "nodename",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$instance:9100\"}, nodename)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(up{job=~\"$job\",servicetype=~\"$servicetype\", purpose!~\"update_message\"}, region)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\",servicetype=~\"$servicetype\", purpose!~\"update_message\", region=~\"$region\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "nodeID",
    "label": "nodeID",
    "query": {
     "query": "label_values(aptos_connections{direction=\"inbound\"},peer_id)"
    }
   },
   {
    "name": "chainAPI",
    "query": {
     "query": "CollectionLookup(mainnet,mainnet.aptoslabs.com,llt,testnet.aptoslabs.com,$chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Parameters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sync Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_sync_peers{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "Block Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "nethermind_blocks{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(nethermind_json_rpc_bytes_sent{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "RPC Sent"
    },
    {
     "expr": "rate(nethermind_json_rpc_bytes_received{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "RPC Received"
    },
    {
     "expr": "rate(nethermind_discovery_bytes_received{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Dscv Sent"
    },
    {
     "expr": "rate(nethermind_discovery_bytes_sent{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Dscv Received"
    },
    {
     "expr": "rate(nethermind_p2pbytes_received{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "P2P Received"
    },
    {
     "expr": "rate(nethermind_p2pbytes_sent{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "P2P Sent"
    }
   ]
  },
  {
   "title": "Version",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "nethermind_version{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "AuRa Specific",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blocks Sealed (total)",
   "type": "stat",
   "description": "Total number of sealed blocks",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_blocks_sealed{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "Failed Block Seals (total)",
   "type": "stat",
   "description": "Total number of failed block seals",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_failed_block_seals{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "Aura Step",
   "type": "timeseries",
   "description": "Current AuRa step",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "nethermind_au_ra_step{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "Blocks Production Indicator",
   "type": "stat",
   "description": "Indicator if blocks can be produced",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_can_produce_blocks{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "Reported Malicious Misbehaviour",
   "type": "stat",
   "description": "Number of reported malicious misbehaviour validators",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_reported_malicious_misbehaviour{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "Sealed Transactions",
   "type": "timeseries",
   "description": "Number of sealed transactions generated by engine",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "nethermind_sealed_transactions{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "Reported Benign Misbehaviour",
   "type": "stat",
   "description": "Number of reported benign misbehaviour validators",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_reported_benign_misbehaviour{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "Validators Count",
   "type": "stat",
   "description": "Number of current AuRa validators",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_validators_count{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "RANDAO Reveal Number",
   "type": "timeseries",
   "description": "RANDAO number of reveal number transactions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "nethermind_reveal_number{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "POSDAO Emit Initiate Change",
   "type": "timeseries",
   "description": "POSDAO number of emit init change transactions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "nethermind_emit_initiate_change{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "RANDAO Commit Hash Transaction",
   "type": "timeseries",
   "description": "RANDAO number of commit hash transactions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "nethermind_commit_hash_transaction{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "Pruning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Caching Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "nethermind_loaded_from_db_nodes_count{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "DB"
    },
    {
     "expr": "nethermind_loaded_from_rlp_cache_nodes_count{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "RLP Cache"
    },
    {
     "expr": "nethermind_loaded_from_cache_nodes_count{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Node Cache"
    }
   ]
  },
  {
   "title": "Pruning Cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "nethermind_memory_used_by_cache{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "Pruning Levels",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "nethermind_committed_nodes_count{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "nethermind_persisted_node_count{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Persisted"
    },
    {
     "expr": "nethermind_cached_nodes_count{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "nethermind_replaced_nodes_count{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Replaced"
    },
    {
     "expr": "nethermind_pruned_persisted_nodes_count{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Pruned Persisted"
    },
    {
     "expr": "nethermind_pruned_transient_nodes_count{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Pruned Transient"
    }
   ]
  },
  {
   "title": "Times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "nethermind_snapshot_persistence_time{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Persistence"
    },
    {
     "expr": "nethermind_pruning_time{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Pruning"
    },
    {
     "expr": "nethermind_deep_pruning_time{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Deep pruning"
    }
   ]
  },
  {
   "title": "Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block processing time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "nethermind_last_block_processing_time_in_ms{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "Blocks (per second)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "rate(nethermind_blocks{job=\"$job\",instance=\"$instance:8550\"}[1m])",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Sync Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "nethermind_sync_peers{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Sync Peers"
    }
   ]
  },
  {
   "title": "State Synced (in bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "nethermind_state_synced{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "State"
    },
    {
     "expr": "rate(nethermind_state_synced{job=\"$job\",instance=\"$instance:8550\"}[60m])*3600",
     "legendFormat": "Rate 60m State"
    }
   ]
  },
  {
   "title": "Fast Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "nethermind_fast_headers{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Headers"
    },
    {
     "expr": "nethermind_fast_bodies{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Bodies"
    },
    {
     "expr": "nethermind_fast_receipts{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Receipts"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "nethermind_blocks{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  },
  {
   "title": "CPU time (tracks restarts)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "JSON RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JSON RPC (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 129 },
   "targets": [
    {
     "expr": "rate(nethermind_json_rpc_successes{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "RPC Successes"
    },
    {
     "expr": "rate(nethermind_json_rpc_errors{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "RPC Errors"
    },
    {
     "expr": "rate(nethermind_json_rpc_request_deserialization_failures{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Deserialization Failures"
    },
    {
     "expr": "rate(nethermind_json_rpc_invalid_requests{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Invalid Requests"
    }
   ]
  },
  {
   "title": "JSON RPC (total)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 136 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "nethermind_json_rpc_requests{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "RPC Requests"
    },
    {
     "expr": "nethermind_json_rpc_successes{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "RPC Successes"
    },
    {
     "expr": "nethermind_json_rpc_errors{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "RPC Errors"
    },
    {
     "expr": "nethermind_json_rpc_request_deserialization_failures{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Deserialization Failures"
    },
    {
     "expr": "nethermind_json_rpc_invalid_requests{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Invalid Requests"
    }
   ]
  },
  {
   "title": "Beam",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Beamed Transactions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 144 },
     "targets": [
      {
       "expr": "nethermind_beamed_transactions{job=\"$job\",instance=\"$instance:8550\"}",
       "legendFormat": "Transactions"
      }
     ]
    },
    {
     "title": "Beamed Blocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_beamed_blocks{job=\"$job\",instance=\"$instance:8550\"}",
       "legendFormat": "Blocks"
      }
     ]
    },
    {
     "title": "Beamed Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 151 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_beamed_requests{job=\"$job\",instance=\"$instance:8550\"}",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "Beamed Trie Nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 151 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_beamed_trie_nodes{job=\"$job\",instance=\"$instance:8550\"}",
       "legendFormat": "Trie Nodes"
      }
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receipts DB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 145 },
   "targets": [
    {
     "expr": "nethermind_receipts_db_reads{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Reads"
    },
    {
     "expr": "nethermind_receipts_db_writes{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Code DB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 151 },
   "targets": [
    {
     "expr": "rate(nethermind_code_db_reads{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(nethermind_code_db_writes{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "State Tree",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 157 },
   "targets": [
    {
     "expr": "rate(nethermind_state_tree_reads{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(nethermind_state_tree_writes{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Block Info DB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 163 },
   "targets": [
    {
     "expr": "rate(nethermind_block_infos_db_reads{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(nethermind_block_infos_db_writes{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "State DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 169 },
   "targets": [
    {
     "expr": "rate(nethermind_state_db_reads{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(nethermind_state_db_writes{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Writes"
    },
    {
     "expr": "rate(nethermind_state_db_in_pruning_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Pruning Writes"
    }
   ]
  },
  {
   "title": "Storage Tree",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 177 },
   "targets": [
    {
     "expr": "rate(nethermind_storage_tree_reads{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(nethermind_storage_tree_writes{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Trie Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 184 },
   "targets": [
    {
     "expr": "rate(nethermind_tree_node_rlp_decodings{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "RLP.Encode"
    },
    {
     "expr": "rate(nethermind_tree_node_rlp_encodings{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "RLP.Decode"
    },
    {
     "expr": "rate(nethermind_tree_node_hash_calculations{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Keccak"
    }
   ]
  },
  {
   "title": "Other DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 191 },
   "targets": [
    {
     "expr": "nethermind_other_db_reads{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Reads"
    },
    {
     "expr": "nethermind_other_db_writes{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Blocks DB (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 198 },
   "targets": [
    {
     "expr": "rate(nethermind_blocks_db_reads{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(nethermind_blocks_db_writes{job=\"$job\",instance=\"$instance:8550\"}[1m])*60",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "TxPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 205 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DarkPool",
   "type": "timeseries",
   "description": "Unknown transactions in blocks",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 206 },
   "targets": [
    {
     "expr": "nethermind_dark_pool_ratio_level1{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "Level1 (not known)"
    },
    {
     "expr": "nethermind_dark_pool_ratio_level2{job=\"$job\",instance=\"$instance:8550\"}",
     "legendFormat": "level2 (not pending)"
    }
   ]
  },
  {
   "title": "1559-type transactions ratio",
   "type": "timeseries",
   "description": "Ratio of 1559-type transactions in the block.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nethermind_eip1559transactions_ratio{job=\"$job\",instance=\"$instance:8550\"}"
    }
   ]
  }
 ]
}