{
 "title": "Ethereum_Validator_Status",
 "description": "Beta dashboard for ethereum staking deployment",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "validators", "query": "label_values(up,validator)" },
   {
    "name": "processes",
    "query": "label_values(namedprocess_namegroup_cpu_seconds_total,groupname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Exporter job status - $validators",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{validator=~\"$validators.*\"}",
     "legendFormat": "{{ validator }} {{ job }}"
    }
   ]
  },
  {
   "title": "Geth states",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_known_states{validator=~\"$validators.*\"}",
     "legendFormat": "known - {{validator}}"
    },
    {
     "expr": "geth_pulled_states{validator=~\"$validators.*\"}",
     "legendFormat": "pulled - {{validator}}"
    }
   ]
  },
  {
   "title": "Lighthouse Validator Clients Enabled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vc_validators_enabled_count", "legendFormat": "{{ validator }}" }
   ]
  },
  {
   "title": "ETH1 endpoint request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(eth1_endpoint_requests [1m])",
     "legendFormat": "{{ endpoint }} requests for {{ validator }}"
    },
    {
     "expr": "eth1_endpoint_errors",
     "legendFormat": "{{ endpoint }} errors for {{ validator }}"
    }
   ]
  },
  {
   "title": "Host info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Lighthouse Beacon DB Size - $validators",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "store_disk_db_size{validator=~\"$validators.*\"}",
       "legendFormat": "{{ validator }}"
      }
     ]
    },
    {
     "title": "Number of the last block checked for deposits",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "eth1_highest_processed_deposit_block{validator=~\"$validators\"}",
       "legendFormat": "{{ validator }}"
      }
     ]
    },
    {
     "title": "Process resident memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\", validator=~\"$validators.*\"}",
       "legendFormat": "{{ groupname }} - {{ validator }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Peers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Geth P2P peers - $validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "p2p_peers{validator=~\"$validators.*\"}",
     "legendFormat": "{{ validator }}"
    }
   ]
  },
  {
   "title": "Lighthouse Beacon Sync Peers - $validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync_peers_per_status{validator=~\"$validators.*\"}",
     "legendFormat": "{{ sync_status }} - {{ validator }}"
    }
   ]
  }
 ]
}