{
 "title": "Hardware_All",
 "tags": [ "Hardware" ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Disk used",
   "type": "timeseries",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype=~\"ext4\",mountpoint=~\"/\"}-node_filesystem_free_bytes{fstype=~\"ext4\",mountpoint=~\"/\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext4\",mountpoint=~\"/\"}+(node_filesystem_size_bytes{fstype=~\"ext4\",mountpoint=~\"/\"}-node_filesystem_free_bytes{fstype=~\"ext4\",mountpoint=~\"/\"}))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "timeseries",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])) by (node_name, instance)) * 100",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes))) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[$__rate_interval])*8",
     "legendFormat": "{{job}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[$__rate_interval])*8",
     "legendFormat": "{{job}}_transmit"
    }
   ]
  }
 ]
}