{
 "title": "Hardware_Disk_Usage_All",
 "tags": [
  "Hardware",
  "Disk_Usage"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{}, chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\"}, network)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(up{chain=~\"$chain\", network=~\"$network\"}, region)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{chain=~\"$chain\", network=~\"$network\", region=~\"$region\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "nodeID",
    "label": "nodeID",
    "query": {
     "query": "label_values(aptos_connections{direction=\"inbound\"},peer_id)"
    }
   },
   {
    "name": "chainAPI",
    "query": {
     "query": "CollectionLookup(mainnet,mainnet.aptoslabs.com,llt,testnet.aptoslabs.com,$chain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Disk Overview [$chain]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "chain" },
  {
   "title": "[$chain] Mainnet Instance Disk Size per mount point",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes {chain=~\"$chain\", network=\"mainnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{chain=~\"$chain\", network=\"mainnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{chain=~\"$chain\", network=\"mainnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{instance}} {{servicetype}} [{{region}}] : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "[$chain] Testnet Instance Disk Space (%)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes {chain=~\"$chain\", network=\"testnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{chain=~\"$chain\", network=\"testnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{chain=~\"$chain\", network=\"testnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{instance}} {{servicetype}} [{{region}}] : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "[$chain] Mainnet Instance Disk Space (%)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{chain=~\"$chain\", network=\"mainnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{chain=~\"$chain\", network=\"mainnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {chain=~\"$chain\", network=\"mainnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{chain=~\"$chain\", network=\"mainnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{chain=~\"$chain\", network=\"mainnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{instance}} {{servicetype}} [{{region}}] : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "[$chain] Testnet Instance Disk Space (%)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{chain=~\"$chain\", network=\"testnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{chain=~\"$chain\", network=\"testnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {chain=~\"$chain\", network=\"testnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{chain=~\"$chain\", network=\"testnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{chain=~\"$chain\", network=\"testnet\", instance=~\"$instance:9100\",mountpoint!=\"/boot\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{instance}} {{servicetype}} [{{region}}] : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "[$chain] Mainnet Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{chain=~\"$chain\", network=\"mainnet\", instance=~\"$instance:9100\",device!~'rootfs',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"} - node_filesystem_avail_bytes{chain=~\"$chain\", network=\"mainnet\", instance=~\"$instance:9100\",device!~'rootfs',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}",
     "legendFormat": "{{instance}} {{servicetype}} [{{region}}] : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "[$chain] Testnet Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{chain=~\"$chain\", network=\"testnet\", instance=~\"$instance:9100\",device!~'rootfs',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"} - node_filesystem_avail_bytes{chain=~\"$chain\", network=\"testnet\", instance=~\"$instance:9100\",device!~'rootfs',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}",
     "legendFormat": "{{instance}} {{servicetype}} [{{region}}] : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "[$chain] Mainnet Disk Space Change for [$interval]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "-delta(node_filesystem_avail_bytes{chain=~\"$chain\", network=\"mainnet\", instance=~\"$instance:9100\",device!~'rootfs',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}[$interval])",
     "legendFormat": "{{instance}} {{servicetype}} [{{region}}] : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "[$chain] Testnet Disk Space Change for [$interval]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "-delta(node_filesystem_avail_bytes{chain=~\"$chain\", network=\"testnet\", instance=~\"$instance:9100\",device!~'rootfs',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}[$interval])",
     "legendFormat": "{{instance}} {{servicetype}} [{{region}}] : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "[$chain] Mainnet Disk Space Change Ratio (%) for [$interval]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "-delta(node_filesystem_avail_bytes{chain=~\"$chain\", network=\"mainnet\", instance=~\"$instance:9100\",device!~'rootfs',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}[$interval])/node_filesystem_size_bytes * 100",
     "legendFormat": "{{instance}} {{servicetype}} [{{region}}] : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "[$chain] Testnet Disk Space Change Ratio (%) for [$interval]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "-delta(node_filesystem_avail_bytes{chain=~\"$chain\", network=\"testnet\", instance=~\"$instance:9100\",device!~'rootfs',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}[$interval])/node_filesystem_size_bytes * 100",
     "legendFormat": "{{instance}} {{servicetype}} [{{region}}] : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "[$chain] Mainnet Disk R/W (kb/sec by device) [$interval]",
   "type": "timeseries",
   "description": "The number of kibibytes read and written to the device  per second",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device!~\"md.*\",chain=~\"$chain\", network=\"mainnet\", instance=~\"$instance:9100\"}[$interval])",
     "legendFormat": "{{instance}} {{servicetype}} [{{region}}] : {{mountpoint}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device!~\"md.*\",chain=~\"$chain\", network=\"mainnet\", instance=~\"$instance:9100\"}[$interval])",
     "legendFormat": "{{chain}} {{network}} {{servicetype}} : {{device}} Write"
    }
   ]
  },
  {
   "title": "[$chain] Testnet Disk R/W (kb/sec by device) [$interval]",
   "type": "timeseries",
   "description": "The number of kibibytes read and written to the device  per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device!~\"md.*\",chain=~\"$chain\", network=\"testnet\", instance=~\"$instance:9100\"}[$interval])",
     "legendFormat": "{{instance}} {{servicetype}} [{{region}}] : {{mountpoint}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device!~\"md.*\",chain=~\"$chain\", network=\"testnet\", instance=~\"$instance:9100\"}[$interval])",
     "legendFormat": "{{chain}} {{network}} {{servicetype}} : {{device}} Write"
    }
   ]
  }
 ]
}