{
 "title": "Hardware_Network_Usage_All",
 "tags": [
  "Hardware",
  "Network_Usage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "🌏 Aptos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Network Bytes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"APT\"} + node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"APT\"}",
     "legendFormat": "[TOTAL] {{chain}} {{network}} {{servicetype}} : {{device}}"
    }
   ]
  },
  {
   "title": "This Month Total Network RX/TX Bytes ",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"APT\"} @ end()) - (node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"APT\"} @ start())",
     "legendFormat": "[RX] {{chain}} {{network}} {{servicetype}} : {{device}}"
    },
    {
     "expr": "(node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"APT\"} @ end()) - (node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"APT\"} @ start())",
     "legendFormat": "[TX] {{chain}} {{network}} {{servicetype}} : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Receive Bytes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"APT\"}",
     "legendFormat": "[RX] {{chain}} {{network}} {{servicetype}} : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Transmit Bytes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"APT\"}",
     "legendFormat": "[TX] {{chain}} {{network}} {{servicetype}} : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Receive Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"APT\"}",
     "legendFormat": "RX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Transmit Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"APT\"}",
     "legendFormat": "TX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic RX (bits/s)",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(irate(node_network_receive_bytes_total{chain=\"APT\", device=~\"en(p[0-9])?(s[0-9])?(f0)?\"}[$__rate_interval])*8)",
     "legendFormat": "RX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic TX (bits/s)",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(irate(node_network_transmit_bytes_total{chain=\"APT\", device=~\"en(p[0-9])?(s[0-9])?(f0)?\"}[$__rate_interval])*8)",
     "legendFormat": "TX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  { "title": "💧 Sui", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Total Network Bytes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"SUI\"} + node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"SUI\"}",
     "legendFormat": "[TOTAL] {{chain}} {{network}} {{servicetype}} : {{device}}"
    }
   ]
  },
  {
   "title": "This Month Total Network RX/TX Bytes ",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"SUI\"} @ end()) - (node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"SUI\"} @ start())",
     "legendFormat": "[RX] {{chain}} {{network}} {{servicetype}} : {{device}}"
    },
    {
     "expr": "(node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"SUI\"} @ end()) - (node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"SUI\"} @ start())",
     "legendFormat": "[TX] {{chain}} {{network}} {{servicetype}} : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Receive Bytes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"SUI\"}",
     "legendFormat": "[RX] {{chain}} {{network}} {{servicetype}} : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Transmit Bytes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"SUI\"}",
     "legendFormat": "[TX] {{chain}} {{network}} {{servicetype}} : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Receive Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"SUI\"}",
     "legendFormat": "RX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Transmit Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"SUI\"}",
     "legendFormat": "TX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic RX (bits/s)",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(irate(node_network_receive_bytes_total{chain=\"SUI\", device=~\"en(p[0-9])?(s[0-9])?(f0)?\"}[$__rate_interval])*8)",
     "legendFormat": "RX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic TX (bits/s)",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(irate(node_network_transmit_bytes_total{chain=\"SUI\", device=~\"en(p[0-9])?(s[0-9])?(f0)?\"}[$__rate_interval])*8)",
     "legendFormat": "TX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  { "title": "⭐️ Nine Chronicles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Total Network Bytes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"NCG\"} + node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"NCG\"}",
     "legendFormat": "[TOTAL] {{chain}} {{network}} {{servicetype}} {{region}} : {{device}}"
    }
   ]
  },
  {
   "title": "This Month Total Network RX Bytes ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"NCG\"} @ end()) - (node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"NCG\"} @ start())",
     "legendFormat": "[RX] {{chain}} {{network}} {{servicetype}} {{region}} {{purpose}} : {{device}}"
    }
   ]
  },
  {
   "title": "This Month Total Network TX Bytes ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"NCG\"} @ end()) - (node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"NCG\"} @ start())",
     "legendFormat": "[TX] {{chain}} {{network}} {{servicetype}} {{region}} {{purpose}} : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Receive Bytes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"NCG\"}",
     "legendFormat": "[RX] {{chain}} {{network}} {{servicetype}} {{region}} {{purpose}} : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Transmit Bytes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"NCG\"}",
     "legendFormat": "[TX] {{chain}} {{network}} {{servicetype}} {{region}} {{purpose}} : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Receive Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"NCG\"}",
     "legendFormat": "RX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Transmit Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"NCG\"}",
     "legendFormat": "TX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic RX (bits/s)",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(irate(node_network_receive_bytes_total{chain=\"NCG\", device=~\"en(p[0-9])?(s[0-9])?(f0)?\"}[$__rate_interval])*8)",
     "legendFormat": "RX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic TX (bits/s)",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(irate(node_network_transmit_bytes_total{chain=\"NCG\", device=~\"en(p[0-9])?(s[0-9])?(f0)?\"}[$__rate_interval])*8)",
     "legendFormat": "TX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  { "title": "🍀 Havah", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Total Network Bytes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"HVH\"} + node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"HVH\"}",
     "legendFormat": "[TOTAL] {{chain}} {{network}} {{servicetype}} : {{device}}"
    }
   ]
  },
  {
   "title": "This Month Total Network RX/TX Bytes ",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"HVH\"} @ end()) - (node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"HVH\"} @ start())",
     "legendFormat": "[RX] {{chain}} {{network}} {{servicetype}} : {{device}}"
    },
    {
     "expr": "(node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"HVH\"} @ end()) - (node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"HVH\"} @ start())",
     "legendFormat": "[TX] {{chain}} {{network}} {{servicetype}} : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Receive Bytes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"HVH\"}",
     "legendFormat": "[RX] {{chain}} {{network}} {{servicetype}} : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Transmit Bytes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"HVH\"}",
     "legendFormat": "[TX] {{chain}} {{network}} {{servicetype}} : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Receive Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"HVH\"}",
     "legendFormat": "RX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  {
   "title": "Total Network Transmit Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=~\"en(p[0-9])?(s[0-9])?(f0)?\", chain=\"HVH\"}",
     "legendFormat": "TX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic RX (bits/s)",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(irate(node_network_receive_bytes_total{chain=\"HVH\", device=~\"en(p[0-9])?(s[0-9])?(f0)?\"}[$__rate_interval])*8)",
     "legendFormat": "RX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic TX (bits/s)",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(irate(node_network_transmit_bytes_total{chain=\"HVH\", device=~\"en(p[0-9])?(s[0-9])?(f0)?\"}[$__rate_interval])*8)",
     "legendFormat": "TX {{chain}} {{network}} {{servicetype}}({{instance}}) : {{device}}"
    }
   ]
  }
 ]
}