{
 "title": "BERA_Validator_Geth_Performance",
 "tags": [ "🚨 P1 ⚠️" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{chain=\"BERA\"}, chain)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\"}, network)"
    }
   },
   {
    "name": "servicetype",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\", network=~\"$network\", servicetype=~\"validator\"}, servicetype)"
    }
   },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{chain=~\"$chain\",network=~\"$network\", servicetype=~\"$servicetype\"},job)"
    }
   },
   {
    "name": "nodename",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$instance:9100\"}, nodename)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\",servicetype=~\"$servicetype\", purpose!~\"update_message\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "nodeID",
    "label": "nodeID",
    "query": {
     "query": "label_values(aptos_connections{direction=\"inbound\"},peer_id)"
    }
   },
   {
    "name": "chainAPI",
    "query": {
     "query": "CollectionLookup(mainnet,mainnet.aptoslabs.com,llt,testnet.aptoslabs.com,$chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Transaction Rate (tx/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(txpool_known{chain=\"$chain\"}[1m])",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "txpool_pending{chain=\"$chain\"}",
     "legendFormat": "transactions"
    }
   ]
  },
  {
   "title": "Geth Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_used{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Geth CPU Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_threads{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Last Received Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Total System Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Geth Processor Loading",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_cpu_procload{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peers{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "p2p_peers{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "RPC Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "rpc_requests{chain=\"$chain\"}"
    }
   ]
  },
  {
   "title": "Network Traffic (bytes/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(p2p_egress{chain=\"$chain\"}[5m])",
     "legendFormat": "Out"
    },
    {
     "expr": "rate(p2p_ingress{chain=\"$chain\"}[5m])",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Outgoing Network (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(p2p_egress{chain=\"$chain\"}[5m])"
    }
   ]
  },
  {
   "title": "Incoming Network (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{chain=\"$chain\"}[5m])"
    }
   ]
  },
  {
   "title": "Disk Activity (bytes/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{chain=\"$chain\"}[5m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(system_disk_writebytes{chain=\"$chain\"}[5m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Read Activity (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{chain=\"$chain\"}[1m])"
    }
   ]
  },
  {
   "title": "Disk Write Activity (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_disk_writebytes{chain=\"$chain\"}[1m])"
    }
   ]
  },
  {
   "title": "Chain Data Disk Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_size{chain=\"$chain\"}"
    }
   ]
  }
 ]
}