{
 "title": "Ethereum_Validator_Ejector",
 "description": "validator-ejector related statistics",
 "tags": [ "🚨 P1 ⚠️" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Valid exit messages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(validator_ejector_exit_messages{valid=\"true\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Exit submission results",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(validator_ejector_exit_actions{result=\"success\"}[$__rate_interval])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(validator_ejector_exit_actions{result=\"error\"}[$__rate_interval])",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Exits left to broadcast",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(validator_ejector_exit_messages_left_number{app=\"validator-ejector\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Invalid exit messages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(validator_ejector_exit_messages{valid=\"false\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Exit security verification",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(validator_ejector_event_security_verification{result=\"success\"}[$__rate_interval])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(validator_ejector_event_security_verification{result=\"error\"}[$__rate_interval])",
     "legendFormat": "Error"
    }
   ]
  }
 ]
}