{
 "title": "Ethereum_Node_Status",
 "tags": [ "🚨 P1 ⚠️" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Execution Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GETH",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{chain=\"ETH\", job=~\".+geth\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "description": "Peers connected with our execution client. Also number of peers we dialled and we are serving.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peers{chain=\"ETH\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory used by execution client.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_memory_allocs{chain=\"ETH\", job=~\".+geth\"}[1m])",
     "legendFormat": "alloc"
    },
    {
     "expr": "system_memory_used{chain=\"ETH\", job=~\".+geth\"}",
     "legendFormat": "used"
    },
    {
     "expr": "system_memory_held{chain=\"ETH\", job=~\".+geth\"}",
     "legendFormat": "held"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_sysload{chain=\"ETH\", job=~\".+geth\"}",
     "legendFormat": "system"
    },
    {
     "expr": "system_cpu_syswait{chain=\"ETH\", job=~\".+geth\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "system_cpu_procload{chain=\"ETH\", job=~\".+geth\"}",
     "legendFormat": "geth"
    }
   ]
  },
  {
   "title": "Latest Chain Header",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_header{chain=\"ETH\", job=~\".+geth\"}"
    }
   ]
  },
  { "title": "Beacon Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "LIGHTHOUSE",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Syncing chain counts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sync_eth2_synced{chain=\"ETH\", instance=~\".+5054\"}",
     "legendFormat": "{{range_type}}"
    }
   ]
  },
  {
   "title": "Current Slot",
   "type": "stat",
   "description": "Lighthouse's reported current slot (unsafe not finalised)",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(slotclock_present_slot{chain=\"ETH\", instance=~\".+5054\"})"
    }
   ]
  },
  {
   "title": "Peer Sync Status",
   "type": "piechart",
   "description": "The sync status for lighthouse's peers",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync_peers_per_status{chain=\"ETH\", instance=~\".+5054\"}",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  {
   "title": "Peer Type",
   "type": "piechart",
   "description": "Peers that have dialed us. Indicates if our node is reachable",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_inbound_peers{chain=\"ETH\", instance=~\".+5054\"}",
     "legendFormat": "Inbound"
    },
    {
     "expr": "network_outbound_peers{chain=\"ETH\", instance=~\".+5054\"}",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Eth1 Execution Client Connected",
   "type": "stat",
   "description": "Identifies if there is an upstream execution client connected",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sync_eth1_connected{chain=\"ETH\", instance=~\".+5054\"}",
     "legendFormat": "{{range_type}}"
    }
   ]
  },
  {
   "title": "Eth2 Consensus Client Synced",
   "type": "stat",
   "description": "Identifies if the consensus client is synced",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sync_eth2_synced{chain=\"ETH\", instance=~\".+5054\"}",
     "legendFormat": "{{range_type}}"
    }
   ]
  },
  { "title": "Charon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CHARON",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Health Status",
   "type": "stat",
   "description": "Status returned from the `/readyz` health status endpoint. Unhealthy reasons include beacon node problems, charon p2p problems, or validator client problems.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_monitoring_readyz{chain=\"ETH\", instance=~\".+3620\"}"
    }
   ]
  },
  {
   "title": "Cluster Duty Success(%) ",
   "type": "gauge",
   "description": "Successful cluster duty percentage by type over the whole time range",
   "gridPos": { "h": 7, "w": 14, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    sum(increase(core_tracker_success_duties_total{chain=\"ETH\", instance=~\".+3620\"}[$__range])) by (duty)\n) \n/ \n( \n    sum(increase(core_tracker_expect_duties_total{chain=\"ETH\", instance=~\".+3620\"}[$__range])) by (duty) \n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beacon Node Score",
   "type": "gauge",
   "description": "Average beacon node score for the whole time window. The score is a combination of:\n - **errors**: the ratio or errors returned by the beacon node \n - **latency**: how fast or slow the beacon node is responding\n\n\nThe performance of the Beacon node is critical to the performance of the validators and therefore rewards.  ",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(clamp(app_monitoring_readyz{chain=\"ETH\", instance=~\".+3620\"} == 1 OR app_monitoring_readyz{chain=\"ETH\", instance=~\".+3620\"} == 4 OR app_monitoring_readyz{chain=\"ETH\", instance=~\".+3620\"} == 5 OR app_monitoring_readyz{chain=\"ETH\", instance=~\".+3620\"} == 6, 1, 1) OR on() vector(0))\n*\n(\n    (\n0.5 * (1.0 - 10*(sum(increase(app_eth2_errors_total{chain=\"ETH\", instance=~\".+3620\"}[$__range])) / (sum(increase(app_eth2_latency_seconds_count{chain=\"ETH\", instance=~\".+3620\"}[$__range]))))) OR on() vector(0.5)\n    )\n    +\n    (\n        0.5 * (1.0 - clamp_max(histogram_quantile(0.99, sum(rate(app_eth2_latency_seconds_bucket{chain=\"ETH\", instance=~\".+3620\"}[$__range])) by (le)),1))\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Info",
   "type": "stat",
   "description": "Information about the charon cluster.\n\n- **Network**: The blockchain network \n- **Operators/Nodes**: The number of operators or nodes or peers in the charon DV cluster.\n- **Threshold**: The minimum number of participating nodes (also quorum).\n- **Validators**: The number of validators added to the cluster, each validator is staking 32 ETH. ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( 1 * app_version{cluster_hash=\"b1c6af5\", cluster_name=\"Lido x Obol: Dazzling Duck\", cluster_network=\"mainnet\", cluster_peer=\"vibrant-shape\"} )\nor \n( 2 * app_version{cluster_hash=\"b1c6af5\", cluster_name=\"Lido x Obol: Dazzling Duck\", cluster_network=\"mainnet\", cluster_peer=\"vibrant-shape\"} )\nor\n( 3 * app_version{cluster_hash=\"b1c6af5\", cluster_name=\"Lido x Obol: Dazzling Duck\", cluster_network=\"mainnet\", cluster_peer=\"vibrant-shape\"} )\nor\n( 4 * app_version{cluster_hash=\"b1c6af5\", cluster_name=\"Lido x Obol: Dazzling Duck\", cluster_network=\"mainnet\", cluster_peer=\"vibrant-shape\"} )",
     "legendFormat": "Network"
    },
    {
     "expr": "cluster_operators{cluster_hash=\"b1c6af5\", cluster_name=\"Lido x Obol: Dazzling Duck\", cluster_network=\"mainnet\", cluster_peer=\"vibrant-shape\"}",
     "legendFormat": "Operators/Nodes"
    },
    {
     "expr": "cluster_threshold{cluster_hash=\"b1c6af5\", cluster_name=\"Lido x Obol: Dazzling Duck\", cluster_network=\"mainnet\", cluster_peer=\"vibrant-shape\"}",
     "legendFormat": "Threshold"
    },
    {
     "expr": "core_scheduler_validators_active{cluster_hash=\"b1c6af5\", cluster_name=\"Lido x Obol: Dazzling Duck\", cluster_network=\"mainnet\", cluster_peer=\"vibrant-shape\"}",
     "legendFormat": "Validators Active"
    },
    {
     "expr": "cluster_validators{cluster_hash=\"b1c6af5\", cluster_name=\"Lido x Obol: Dazzling Duck\", cluster_network=\"mainnet\", cluster_peer=\"vibrant-shape\"}",
     "legendFormat": "Validators Total"
    }
   ]
  },
  {
   "title": "Peer Connectivity and Missed Duties (🚧)",
   "type": "table",
   "description": "- **Peer**: The peer's name (inferred from their *charon-enr-private-key*)\n- **You**: ⭐️ is this local charon node\n- **Connected**: Whether you are currently connected to this peer.\n- **Direct**: Whether the connection is *direct* (👍) or *relay* (👎) \n- **Latency**: The time messages take to travel to/from the peer.\n- **Version**: The version of the peer's charon node\n- **Supported**: Whether the peers charon version is supported/compatible or not.\n- **Uptime**\" The duration since peer was restarted.\n- **🚧Attest**: Number of attestation duties missed in the time window.\n- **🚧Propose**: Number of block proposal duties missed in the time window.\n- **🚧Other**: Number of other duties missed in the time window.\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(p2p_ping_success{chain=\"ETH\", instance=~\".+3620\"}) by (peer)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket{chain=\"ETH\", instance=~\".+3620\"}[$__rate_interval])) by (le,peer))  * 1000"
    },
    {
     "expr": "sum(p2p_ping_success{chain=\"ETH\", instance=~\".+3620\"}) by (peer)"
    },
    {
     "expr": "(max(p2p_peer_connection_types{chain=\"ETH\", instance=~\".+3620\",type=\"direct\"}) by (peer)*10 + \nmax(p2p_peer_connection_types{chain=\"ETH\", instance=~\".+3620\",type=\"relay\"}) by (peer))"
    },
    {
     "expr": "sum(app_peerinfo_version{chain=\"ETH\", instance=~\".+3620\"}) by (peer,version) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max(app_peerinfo_start_time_secs{chain=\"ETH\", instance=~\".+3620\"} > 0) by (peer)"
    },
    {
     "expr": "max(app_peerinfo_index{chain=\"ETH\", instance=~\".+3620\"}) by (peer)"
    },
    {
     "expr": "(\n    sum(increase(core_tracker_participation_missed_total{chain=\"ETH\", instance=~\".+3620\", duty=\"attester\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{chain=\"ETH\", instance=~\".+3620\", duty=\"attester\"}[$__range])) by (peer) \n) OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n    sum(increase(core_tracker_participation_missed_total{chain=\"ETH\", instance=~\".+3620\", duty=~\".*proposer\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{chain=\"ETH\", instance=~\".+3620\", duty=~\".*proposer\"}[$__range])) by (peer) \n) OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n    sum(increase(core_tracker_participation_missed_total{chain=\"ETH\", instance=~\".+3620\", duty!~\"(proposer|attester)\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{chain=\"ETH\", instance=~\".+3620\", duty!~\"(proposer|attester)\"}[$__range])) by (peer) \n) OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(app_peerinfo_version_support{chain=\"ETH\", instance=~\".+3620\"}) by (peer) "
    }
   ]
  },
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "LODESTAR",
   "type": "stat",
   "description": "A lodestar validator client serving as part of this distributed validator cluster.",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vc_indices_count" }
   ]
  },
  {
   "title": "Attestations Published",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vc_published_attestations_total",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Blocks Published",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "vc_block_published_total" }
   ]
  },
  {
   "title": "Aggregate Attestations Published",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "vc_published_aggregates_total", "legendFormat": "{{outcome}}" }
   ]
  }
 ]
}